#include "defines.h"

struct Habitat
{
	const struct HabitatPage* page;
	u32 numPages;
};

struct HabitatPage
{
	const u16* mons;
	u32 numMons;
};

const u16 gGrasslandPage1[] =
{
	SPECIES_RATTATA,
	SPECIES_RATICATE,
	SPECIES_SENTRET,
	SPECIES_FURRET,
};

const u16 gGrasslandPage2[] =
{
	SPECIES_ZIGZAGOON,
	SPECIES_LINOONE,
	SPECIES_POOCHYENA,
	SPECIES_MIGHTYENA,
};

const u16 gGrasslandPage3[] =
{
	SPECIES_ZIGZAGOON_G,
	SPECIES_LINOONE_G,
	SPECIES_OBSTAGOON,
};

const u16 gGrasslandPage4[] =
{
	SPECIES_NIDORAN_F,
	SPECIES_NIDORINA,
	SPECIES_NIDOQUEEN,
};

const u16 gGrasslandPage5[] =
{
	SPECIES_NIDORAN_M,
	SPECIES_NIDORINO,
	SPECIES_NIDOKING,
};

const u16 gGrasslandPage6[] =
{
	SPECIES_DODUO,
	SPECIES_DODRIO,
	SPECIES_TAILLOW,
	SPECIES_SWELLOW,
};

const u16 gGrasslandPage7[] =
{
	SPECIES_TANGELA,
	SPECIES_TANGROWTH,
	SPECIES_SUNKERN,
	SPECIES_SUNFLORA,
};

const u16 gGrasslandPage8[] =
{
	SPECIES_HOPPIP,
	SPECIES_SKIPLOOM,
	SPECIES_JUMPLUFF,
};

const u16 gGrasslandPage9[] =
{
	SPECIES_ODDISH,
	SPECIES_GLOOM,
	SPECIES_VILEPLUME,
	SPECIES_BELLOSSOM,
};

const u16 gGrasslandPage10[] =
{
	SPECIES_EKANS,
	SPECIES_ARBOK,
	SPECIES_SCYTHER,
	SPECIES_SCIZOR,
};

const u16 gGrasslandPage11[] =
{
	SPECIES_IGGLYBUFF,
	SPECIES_JIGGLYPUFF,
	SPECIES_WIGGLYTUFF,
};

const u16 gGrasslandPage12[] =
{
	SPECIES_MAREEP,
	SPECIES_FLAAFFY,
	SPECIES_AMPHAROS,
};

const u16 gGrasslandPage13[] =
{
	SPECIES_FARFETCHD,
	SPECIES_FARFETCHD_G,
	SPECIES_SIRFETCHD,
};

const u16 gGrasslandPage14[] =
{
	SPECIES_LICKITUNG,
	SPECIES_LICKILICKY,
};

const u16 gGrasslandPage15[] =
{
	SPECIES_BUDEW,
	SPECIES_ROSELIA,
	SPECIES_ROSERADE,
};

const u16 gGrasslandPage16[] =
{
	SPECIES_DROWZEE,
	SPECIES_HYPNO,
	SPECIES_GULPIN,
	SPECIES_SWALOT,
};

const u16 gGrasslandPage17[] =
{
	SPECIES_KANGASKHAN,
	SPECIES_GIRAFARIG,
	SPECIES_TAUROS,
	SPECIES_MILTANK,
};

const u16 gGrasslandPage18[] =
{
	SPECIES_BUNNELBY,
	SPECIES_DIGGERSBY,
	SPECIES_YUNGOOS,
	SPECIES_GUMSHOOS,
};

const u16 gGrasslandPage19[] =
{
	SPECIES_VULPIX,
	SPECIES_NINETALES,
	SPECIES_PONYTA,
	SPECIES_RAPIDASH,
};

const u16 gGrasslandPage20[] =
{
	SPECIES_ELEKID,
	SPECIES_ELECTABUZZ,
	SPECIES_ELECTIVIRE,
};

const u16 gGrasslandPage21[] =
{
	SPECIES_ZANGOOSE,
	SPECIES_SEVIPER,
};

const u16 gGrasslandPage22[] =
{
	SPECIES_ELECTRIKE,
	SPECIES_MANECTRIC,
	SPECIES_PLUSLE,
	SPECIES_MINUN,
};

const u16 gGrasslandPage23[] =
{
	SPECIES_GROWLITHE,
	SPECIES_ARCANINE,
	SPECIES_LITLEO,
	SPECIES_PYROAR,
};

const u16 gGrasslandPage24[] =
{
	SPECIES_CASTFORM,
	SPECIES_CHINGLING,
	SPECIES_CHIMECHO,
};

const u16 gGrasslandPage25[] =
{
	SPECIES_BULBASAUR,
	SPECIES_IVYSAUR,
	SPECIES_VENUSAUR,
};

const u16 gGrasslandPage26[] =
{
	SPECIES_CHIKORITA,
	SPECIES_BAYLEEF,
	SPECIES_MEGANIUM,
};

const u16 gGrasslandPage27[] =
{
	SPECIES_CYNDAQUIL,
	SPECIES_QUILAVA,
	SPECIES_TYPHLOSION,
	SPECIES_TYPHLOSION_H,
};

const u16 gGrasslandPage28[] =
{
	SPECIES_TORCHIC,
	SPECIES_COMBUSKEN,
	SPECIES_BLAZIKEN,
};

const u16 gGrasslandPage29[] =
{
	SPECIES_RAIKOU,
	SPECIES_ENTEI,
	SPECIES_SUICUNE,
};

const u16 gGrasslandPage30[] =
{
	SPECIES_TURTWIG,
	SPECIES_GROTLE,
	SPECIES_TORTERRA,
};

const u16 gGrasslandPage31[] =
{
	SPECIES_STARLY,
	SPECIES_STARAVIA,
	SPECIES_STARAPTOR,
};

const u16 gGrasslandPage32[] =
{
	SPECIES_BIDOOF,
	SPECIES_BIBAREL,
	SPECIES_KRICKETOT,
	SPECIES_KRICKETUNE,
};

const u16 gGrasslandPage33[] =
{
	SPECIES_SHINX,
	SPECIES_LUXIO,
	SPECIES_LUXRAY,
	SPECIES_PACHIRISU,
};

const u16 gGrasslandPage34[] =
{
	SPECIES_BUNEARY,
	SPECIES_LOPUNNY,
	SPECIES_GLAMEOW,
	SPECIES_PURUGLY,
};

const u16 gGrasslandPage35[] =
{
	SPECIES_SNIVY,
	SPECIES_SERVINE,
	SPECIES_SERPERIOR,
};

const u16 gGrasslandPage36[] =
{
	SPECIES_PATRAT,
	SPECIES_WATCHOG,
	SPECIES_PURRLOIN,
	SPECIES_LIEPARD,
};

const u16 gGrasslandPage37[] =
{
	SPECIES_LILLIPUP,
	SPECIES_HERDIER,
	SPECIES_STOUTLAND,
	SPECIES_BOUFFALANT,
};

const u16 gGrasslandPage38[] =
{
	SPECIES_BLITZLE,
	SPECIES_ZEBSTRIKA,
	SPECIES_MINCCINO,
	SPECIES_CINCCINO,
};

const u16 gGrasslandPage39[] =
{
	SPECIES_FLETCHLING,
	SPECIES_FLETCHINDER,
	SPECIES_TALONFLAME,
};

const u16 gGrasslandPage40[] =
{
	SPECIES_FLABEBE,
	SPECIES_FLOETTE,
	SPECIES_FLORGES,
	SPECIES_FLOETTE_ETERNAL,
};

const u16 gGrasslandPage41[] =
{
	SPECIES_FLABEBE_BLUE,
	SPECIES_FLOETTE_BLUE,
	SPECIES_FLORGES_BLUE,
};

const u16 gGrasslandPage42[] =
{
	SPECIES_FLABEBE_ORANGE,
	SPECIES_FLOETTE_ORANGE,
	SPECIES_FLORGES_ORANGE,
};

const u16 gGrasslandPage43[] =
{
	SPECIES_FLABEBE_YELLOW,
	SPECIES_FLOETTE_YELLOW,
	SPECIES_FLORGES_YELLOW,
};

const u16 gGrasslandPage44[] =
{
	SPECIES_FLABEBE_WHITE,
	SPECIES_FLOETTE_WHITE,
	SPECIES_FLORGES_WHITE,
};

const u16 gGrasslandPage45[] =
{
	SPECIES_SKIDDO,
	SPECIES_GOGOAT,
	SPECIES_PANCHAM,
	SPECIES_PANGORO,
};

const u16 gGrasslandPage46[] =
{
	SPECIES_FURFROU,
	SPECIES_FURFROU_HEART,
	SPECIES_FURFROU_STAR,
	SPECIES_FURFROU_DIAMOND,
};

const u16 gGrasslandPage47[] =
{
	SPECIES_FURFROU_DEBUTANTE,
	SPECIES_FURFROU_MATRON,
	SPECIES_FURFROU_DANDY,
};

const u16 gGrasslandPage48[] =
{
	SPECIES_FURFROU_LA_REINE,
	SPECIES_FURFROU_KABUKI,
	SPECIES_FURFROU_PHAROAH,
};

const u16 gGrasslandPage49[] =
{
	SPECIES_ESPURR,
	SPECIES_MEOWSTIC,
	SPECIES_MEOWSTIC_FEMALE,
};

const u16 gGrasslandPage50[] =
{
	SPECIES_SPRITZEE,
	SPECIES_AROMATISSE,
	SPECIES_SWIRLIX,
	SPECIES_SLURPUFF,
};

const u16 gGrasslandPage51[] =
{
	SPECIES_PIKIPEK,
	SPECIES_TRUMBEAK,
	SPECIES_TOUCANNON,
};

const u16 gGrasslandPage52[] =
{
	SPECIES_GRUBBIN,
	SPECIES_CHARJABUG,
	SPECIES_VIKAVOLT,
};

const u16 gGrasslandPage53[] =
{
	SPECIES_MUDBRAY,
	SPECIES_MUDSDALE,
	SPECIES_STUFFUL,
	SPECIES_BEWEAR,
};

const u16 gGrasslandPage54[] =
{
	SPECIES_SKWOVET,
	SPECIES_GREEDENT,
	SPECIES_WOOLOO,
	SPECIES_DUBWOOL,
};

const u16 gGrasslandPage55[] =
{
	SPECIES_NICKIT,
	SPECIES_THIEVUL,
	SPECIES_GOSSIFLEUR,
	SPECIES_ELDEGOSS,
};

const u16 gGrasslandPage56[] =
{
	SPECIES_BLIPBUG,
	SPECIES_DOTTLER,
	SPECIES_ORBEETLE,
};

const u16 gGrasslandPage57[] =
{
	SPECIES_YAMPER,
	SPECIES_BOLTUND,
	SPECIES_MORPEKO,
	SPECIES_MORPEKO_HANGRY,
};

const u16 gGrasslandPage58[] =
{
	SPECIES_KLEAVOR,
};

const u16 gGrasslandPage59[] =
{
	SPECIES_GROWLITHE_H,
	SPECIES_ARCANINE_H,
};

const u16 gForestPage1[] =
{
	SPECIES_CATERPIE,
	SPECIES_METAPOD,
	SPECIES_BUTTERFREE,
};

const u16 gForestPage2[] =
{
	SPECIES_WEEDLE,
	SPECIES_KAKUNA,
	SPECIES_BEEDRILL,
};

const u16 gForestPage3[] =
{
	SPECIES_WURMPLE,
	SPECIES_SILCOON,
	SPECIES_BEAUTIFLY,
};

const u16 gForestPage4[] =
{
	SPECIES_CASCOON,
	SPECIES_DUSTOX,
};

const u16 gForestPage5[] =
{
	SPECIES_PIDGEY,
	SPECIES_PIDGEOTTO,
	SPECIES_PIDGEOT,
};

const u16 gForestPage6[] =
{
	SPECIES_HOOTHOOT,
	SPECIES_NOCTOWL,
	SPECIES_NATU,
	SPECIES_XATU,
};

const u16 gForestPage7[] =
{
	SPECIES_PICHU,
	SPECIES_PIKACHU,
	SPECIES_RAICHU,
	SPECIES_RAICHU_A,
};

const u16 gForestPage8[] =
{
	SPECIES_PICHU_SPIKY
};

const u16 gForestPage8_1[] =
{
	SPECIES_PIKACHU_SURFING,
	SPECIES_PIKACHU_FLYING,
};

const u16 gForestPage8_2[] =
{
	SPECIES_PIKACHU_COSPLAY,
	SPECIES_PIKACHU_LIBRE,
	SPECIES_PIKACHU_POP_STAR,
};

const u16 gForestPage8_3[] =
{
	SPECIES_PIKACHU_ROCK_STAR,
	SPECIES_PIKACHU_BELLE,
	SPECIES_PIKACHU_PHD,
};

const u16 gForestPage8_4[] =
{
	SPECIES_PIKACHU_CAP_ORIGINAL,
	SPECIES_PIKACHU_CAP_HOENN,
	SPECIES_PIKACHU_CAP_SINNOH,
	SPECIES_PIKACHU_CAP_UNOVA,
};

const u16 gForestPage8_5[] =
{
	SPECIES_PIKACHU_CAP_KALOS,
	SPECIES_PIKACHU_CAP_ALOLA,
	SPECIES_PIKACHU_CAP_PARTNER,
};

const u16 gForestPage9[] =
{
	SPECIES_BELLSPROUT,
	SPECIES_WEEPINBELL,
	SPECIES_VICTREEBEL,
};

const u16 gForestPage10[] =
{
	SPECIES_PARAS,
	SPECIES_PARASECT,
	SPECIES_SHROOMISH,
	SPECIES_BRELOOM,
};

const u16 gForestPage11[] =
{
	SPECIES_SEEDOT,
	SPECIES_NUZLEAF,
	SPECIES_SHIFTRY,
};

const u16 gForestPage12[] =
{
	SPECIES_VENONAT,
	SPECIES_VENOMOTH,
	SPECIES_YANMA,
	SPECIES_YANMEGA,
};

const u16 gForestPage13[] =
{
	SPECIES_LEDYBA,
	SPECIES_LEDIAN,
	SPECIES_SPINARAK,
	SPECIES_ARIADOS,
};

const u16 gForestPage14[] =
{
	SPECIES_NINCADA,
	SPECIES_NINJASK,
	SPECIES_SHEDINJA,
};

const u16 gForestPage15[] =
{
	SPECIES_VOLBEAT,
	SPECIES_ILLUMISE,
};

const u16 gForestPage16[] =
{
	SPECIES_PINECO,
	SPECIES_FORRETRESS,
};

const u16 gForestPage17[] =
{
	SPECIES_SLAKOTH,
	SPECIES_VIGOROTH,
	SPECIES_SLAKING,
};

const u16 gForestPage18[] =
{
	SPECIES_SKITTY,
	SPECIES_DELCATTY,
};

const u16 gForestPage19[] =
{
	SPECIES_MURKROW,
	SPECIES_HONCHKROW,
	SPECIES_SNEASEL,
	SPECIES_WEAVILE,
};

const u16 gForestPage20[] =
{
	SPECIES_EXEGGCUTE,
	SPECIES_EXEGGUTOR,
	SPECIES_BONSLY,
	SPECIES_SUDOWOODO,
};

const u16 gForestPage21[] =
{
	SPECIES_EXEGGCUTE_A,
	SPECIES_EXEGGUTOR_A,
};

const u16 gForestPage22[] =
{
	SPECIES_AIPOM,
	SPECIES_AMBIPOM,
	SPECIES_STANTLER,
	SPECIES_KECLEON,
	SPECIES_WYRDEER,
};

const u16 gForestPage23[] =
{
	SPECIES_PINSIR,
	SPECIES_HERACROSS,
};

const u16 gForestPage24[] =
{
	SPECIES_SWABLU,
	SPECIES_ALTARIA,
	SPECIES_TROPIUS,
};

const u16 gForestPage25[] =
{
	SPECIES_DUSKULL,
	SPECIES_DUSCLOPS,
	SPECIES_DUSKNOIR,
};

const u16 gForestPage26[] =
{
	SPECIES_TOGEPI,
	SPECIES_TOGETIC,
	SPECIES_TOGEKISS,
};

const u16 gForestPage27[] =
{
	SPECIES_TREECKO,
	SPECIES_GROVYLE,
	SPECIES_SCEPTILE,
};

const u16 gForestPage28[] =
{
	SPECIES_CELEBI,
};

const u16 gForestPage29[] =
{
	SPECIES_CHIMCHAR,
	SPECIES_MONFERNO,
	SPECIES_INFERNAPE,
};

const u16 gForestPage30[] =
{
	SPECIES_BURMY,
	SPECIES_WORMADAM,
	SPECIES_MOTHIM,
	SPECIES_CHATOT,
};

const u16 gForestPage31[] =
{
	SPECIES_BURMY_SANDY,
	SPECIES_BURMY_TRASH,
	SPECIES_WORMADAM_SANDY,
	SPECIES_WORMADAM_TRASH,
};

const u16 gForestPage32[] =
{
	SPECIES_COMBEE,
	SPECIES_VESPIQUEN,
	SPECIES_CHERUBI,
	SPECIES_CHERRIM,
};

const u16 gForestPage33[] =
{
	SPECIES_DRIFLOON,
	SPECIES_DRIFBLIM,
	SPECIES_STUNKY,
	SPECIES_SKUNTANK,
};

const u16 gForestPage34[] =
{
	SPECIES_CRESSELIA,
	SPECIES_DARKRAI,
	SPECIES_SHAYMIN,
	SPECIES_SHAYMIN_SKY,
};

const u16 gForestPage35[] =
{
	SPECIES_PANSAGE,
	SPECIES_SIMISAGE,
	SPECIES_PANSEAR,
	SPECIES_SIMISEAR,
};

const u16 gForestPage36[] =
{
	SPECIES_PANPOUR,
	SPECIES_SIMIPOUR,
};

const u16 gForestPage37[] =
{
	SPECIES_SEWADDLE,
	SPECIES_SWADLOON,
	SPECIES_LEAVANNY,
};

const u16 gForestPage38[] =
{
	SPECIES_VENIPEDE,
	SPECIES_WHIRLIPEDE,
	SPECIES_SCOLIPEDE,
};

const u16 gForestPage39[] =
{
	SPECIES_COTTONEE,
	SPECIES_WHIMSICOTT,
	SPECIES_PETILIL,
	SPECIES_LILLIGANT,
};

const u16 gForestPage40[] =
{
	SPECIES_ZORUA,
	SPECIES_ZOROARK,
};

const u16 gForestPage41[] =
{
	SPECIES_DEERLING,
	SPECIES_DEERLING_SUMMER,
	SPECIES_DEERLING_AUTUMN,
	SPECIES_DEERLING_WINTER,
};

const u16 gForestPage42[] =
{
	SPECIES_SAWSBUCK,
	SPECIES_SAWSBUCK_SUMMER,
	SPECIES_SAWSBUCK_AUTUMN,
	SPECIES_SAWSBUCK_WINTER,
};

const u16 gForestPage43[] =
{
	SPECIES_KARRABLAST,
	SPECIES_ESCAVALIER,
	SPECIES_FOONGUS,
	SPECIES_AMOONGUSS,
};

const u16 gForestPage44[] =
{
	SPECIES_CHESPIN,
	SPECIES_QUILLADIN,
	SPECIES_CHESNAUGHT,
};

const u16 gForestPage45[] =
{
	SPECIES_SCATTERBUG,
	SPECIES_SPEWPA,
	SPECIES_VIVILLON,
	SPECIES_VIVILLON_ARCHIPELAGO,
};

const u16 gForestPage46[] =
{
	SPECIES_VIVILLON_CONTINENTAL,
	SPECIES_VIVILLON_ELEGANT,
	SPECIES_VIVILLON_GARDEN,
	SPECIES_VIVILLON_HIGH_PLAINS,
};

const u16 gForestPage47[] =
{
	SPECIES_VIVILLON_ICY_SNOW,
	SPECIES_VIVILLON_JUNGLE,
	SPECIES_VIVILLON_MARINE,
	SPECIES_VIVILLON_MODERN,
};

const u16 gForestPage48[] =
{
	SPECIES_VIVILLON_MONSOON,
	SPECIES_VIVILLON_OCEAN,
	SPECIES_VIVILLON_TUNDRA,
	SPECIES_VIVILLON_POLAR,
};

const u16 gForestPage49[] =
{
	SPECIES_VIVILLON_RIVER,
	SPECIES_VIVILLON_SANDSTORM,
	SPECIES_VIVILLON_SAVANNA,
	SPECIES_VIVILLON_SUN,
};

const u16 gForestPage50[] =
{
	SPECIES_VIVILLON_POKEBALL,
	SPECIES_VIVILLON_FANCY,
};

const u16 gForestPage51[] =
{
	SPECIES_EMOLGA,
	SPECIES_HAWLUCHA,
	SPECIES_DEDENNE,
};

const u16 gForestPage52[] =
{
	SPECIES_PHANTUMP,
	SPECIES_TREVENANT,
	SPECIES_PUMPKABOO,
	SPECIES_GOURGEIST,
};

const u16 gForestPage53[] =
{
	SPECIES_PUMPKABOO_M,
	SPECIES_PUMPKABOO_L,
	SPECIES_PUMPKABOO_XL,
};

const u16 gForestPage54[] =
{
	SPECIES_GOURGEIST_M,
	SPECIES_GOURGEIST_L,
	SPECIES_GOURGEIST_XL,
};

const u16 gForestPage55[] =
{
	SPECIES_ROWLET,
	SPECIES_DARTRIX,
	SPECIES_DECIDUEYE,
	SPECIES_DECIDUEYE_H,
};

const u16 gForestPage56[] =
{
	SPECIES_ORICORIO,
	SPECIES_ORICORIO_Y,
	SPECIES_ORICORIO_P,
	SPECIES_ORICORIO_S,
};

const u16 gForestPage57[] =
{
	SPECIES_CUTIEFLY,
	SPECIES_RIBOMBEE,
};

const u16 gForestPage58[] =
{
	SPECIES_FOMANTIS,
	SPECIES_LURANTIS,
	SPECIES_MORELULL,
	SPECIES_SHIINOTIC,
};

const u16 gForestPage59[] =
{
	SPECIES_BOUNSWEET,
	SPECIES_STEENEE,
	SPECIES_TSAREENA,
};

const u16 gForestPage60[] =
{
	SPECIES_COMFEY,
	SPECIES_ORANGURU,
	SPECIES_PASSIMIAN,
	SPECIES_KOMALA,
};

const u16 gForestPage61[] =
{
	SPECIES_GROOKEY,
	SPECIES_THWACKEY,
	SPECIES_RILLABOOM,
};

const u16 gForestPage62[] =
{
	SPECIES_APPLIN,
	SPECIES_FLAPPLE,
	SPECIES_APPLETUN,
};

const u16 gForestPage63[] =
{
	SPECIES_PONYTA_G,
	SPECIES_RAPIDASH_G,
	SPECIES_INDEEDEE,
	SPECIES_INDEEDEE_FEMALE,
};

const u16 gForestPage64[] =
{
	SPECIES_HATENNA,
	SPECIES_HATTREM,
	SPECIES_HATTERENE,
};

const u16 gForestPage65[] =
{
	SPECIES_IMPIDIMP,
	SPECIES_MORGREM,
	SPECIES_GRIMMSNARL,
};

const u16 gForestPage66[] =
{
	SPECIES_ZORUA_H,
	SPECIES_ZOROARK_H,
};

const u16 gForestPage67[] =
{
	SPECIES_SNEASEL_H,
	SPECIES_SNEASLER,
	SPECIES_LILLIGANT_H,
};

const u16 gWatersEdgePage1[] =
{
	SPECIES_GOLDEEN,
	SPECIES_SEAKING,
};

const u16 gWatersEdgePage2[] =
{
	SPECIES_MAGIKARP,
	SPECIES_GYARADOS,
	SPECIES_KRABBY,
	SPECIES_KINGLER,
};

const u16 gWatersEdgePage3[] =
{
	SPECIES_CORPHISH,
	SPECIES_CRAWDAUNT,
	SPECIES_BARBOACH,
	SPECIES_WHISCASH,
};

const u16 gWatersEdgePage4[] =
{
	SPECIES_LOTAD,
	SPECIES_LOMBRE,
	SPECIES_LUDICOLO,
};

const u16 gWatersEdgePage5[] =
{
	SPECIES_SURSKIT,
	SPECIES_MASQUERAIN,
};

const u16 gWatersEdgePage6[] =
{
	SPECIES_PSYDUCK,
	SPECIES_GOLDUCK,
	SPECIES_WOOPER,
	SPECIES_QUAGSIRE,
};

const u16 gWatersEdgePage7[] =
{
	SPECIES_POLIWAG,
	SPECIES_POLIWHIRL,
	SPECIES_POLIWRATH,
	SPECIES_POLITOED,
};

const u16 gWatersEdgePage8[] =
{
	SPECIES_AZURILL,
	SPECIES_MARILL,
	SPECIES_AZUMARILL,
};

const u16 gWatersEdgePage9[] =
{
	SPECIES_SLOWPOKE,
	SPECIES_SLOWBRO,
	SPECIES_SLOWKING,
};

const u16 gWatersEdgePage10[] =
{
	SPECIES_SLOWPOKE_G,
	SPECIES_SLOWBRO_G,
	SPECIES_SLOWKING_G,
};

const u16 gWatersEdgePage11[] =
{
	SPECIES_FEEBAS,
	SPECIES_MILOTIC,
};

const u16 gWatersEdgePage12[] =
{
	SPECIES_ANORITH,
	SPECIES_ARMALDO,
};

const u16 gWatersEdgePage13[] =
{
	SPECIES_DRATINI,
	SPECIES_DRAGONAIR,
	SPECIES_DRAGONITE,
};

const u16 gWatersEdgePage14[] =
{
	SPECIES_SQUIRTLE,
	SPECIES_WARTORTLE,
	SPECIES_BLASTOISE,
};

const u16 gWatersEdgePage15[] =
{
	SPECIES_TOTODILE,
	SPECIES_CROCONAW,
	SPECIES_FERALIGATR,
};

const u16 gWatersEdgePage16[] =
{
	SPECIES_MUDKIP,
	SPECIES_MARSHTOMP,
	SPECIES_SWAMPERT,
};

const u16 gWatersEdgePage17[] =
{
	SPECIES_LATIAS,
	SPECIES_LATIOS,
};

const u16 gWatersEdgePage18[] =
{
	SPECIES_PIPLUP,
	SPECIES_PRINPLUP,
	SPECIES_EMPOLEON,
};

const u16 gWatersEdgePage19[] =
{
	SPECIES_BUIZEL,
	SPECIES_FLOATZEL,
};

const u16 gWatersEdgePage20[] =
{
	SPECIES_SHELLOS,
	SPECIES_GASTRODON,
	SPECIES_SHELLOS_EAST,
	SPECIES_GASTRODON_EAST,
};

const u16 gWatersEdgePage21[] =
{
	SPECIES_FINNEON,
	SPECIES_LUMINEON,
};

const u16 gWatersEdgePage22[] =
{
	SPECIES_OSHAWOTT,
	SPECIES_DEWOTT,
	SPECIES_SAMUROTT,
	SPECIES_SAMUROTT_H,
};

const u16 gWatersEdgePage23[] =
{
	SPECIES_TYMPOLE,
	SPECIES_PALPITOAD,
	SPECIES_SEISMITOAD,
};

const u16 gWatersEdgePage24[] =
{
	SPECIES_BASCULIN_RED,
	SPECIES_BASCULIN_BLUE,
	SPECIES_BASCULIN_H,
	SPECIES_BASCULEGION,
};

const u16 gWatersEdgePage25[] =
{
	SPECIES_DUCKLETT,
	SPECIES_SWANNA,
};

const u16 gWatersEdgePage26[] =
{
	SPECIES_SHELMET,
	SPECIES_ACCELGOR,
	SPECIES_STUNFISK,
	SPECIES_STUNFISK_G,
};

const u16 gWatersEdgePage27[] =
{
	SPECIES_FROAKIE,
	SPECIES_FROGADIER,
	SPECIES_GRENINJA,
	SPECIES_ASHGRENINJA,
};

const u16 gWatersEdgePage28[] =
{
	SPECIES_BINACLE,
	SPECIES_BARBARACLE,
};

const u16 gWatersEdgePage29[] =
{
	SPECIES_SKRELP,
	SPECIES_DRAGALGE,
	SPECIES_CLAUNCHER,
	SPECIES_CLAWITZER,
};

const u16 gWatersEdgePage30[] =
{
	SPECIES_GOOMY,
	SPECIES_SLIGGOO,
	SPECIES_GOODRA,
};

const u16 gWatersEdgePage31[] =
{
	SPECIES_POPPLIO,
	SPECIES_BRIONNE,
	SPECIES_PRIMARINA,
};

const u16 gWatersEdgePage32[] =
{
	SPECIES_DEWPIDER,
	SPECIES_ARAQUANID,
	SPECIES_BRUXISH,
};

const u16 gWatersEdgePage33[] =
{
	SPECIES_WIMPOD,
	SPECIES_GOLISOPOD,
	SPECIES_SANDYGAST,
	SPECIES_PALOSSAND,
};

const u16 gWatersEdgePage34[] =
{
	SPECIES_SOBBLE,
	SPECIES_DRIZZILE,
	SPECIES_INTELEON,
};

const u16 gWatersEdgePage35[] =
{
	SPECIES_CHEWTLE,
	SPECIES_DREDNAW,
	SPECIES_ARROKUDA,
	SPECIES_BARRASKEWDA,
};

const u16 gWatersEdgePage36[] =
{
	SPECIES_CLOBBOPUS,
	SPECIES_GRAPPLOCT,
	SPECIES_PINCURCHIN,
};

const u16 gWatersEdgePage37[] =
{
	SPECIES_EISCUE,
	SPECIES_EISCUE_NOICE,
};

const u16 gWatersEdgePage38[] =
{
	SPECIES_DREEPY,
	SPECIES_DRAKLOAK,
	SPECIES_DRAGAPULT,
};
const u16 gWatersEdgePage39[] =
{
	SPECIES_SLIGGOO_H,
	SPECIES_GOODRA_H,
};

const u16 gSeaPage1[] =
{
	SPECIES_TENTACOOL,
	SPECIES_TENTACRUEL,
};

const u16 gSeaPage2[] =
{
	SPECIES_WINGULL,
	SPECIES_PELIPPER,
};

const u16 gSeaPage3[] =
{
	SPECIES_STARYU,
	SPECIES_STARMIE,
};

const u16 gSeaPage4[] =
{
	SPECIES_CHINCHOU,
	SPECIES_LANTURN,
	SPECIES_REMORAID,
	SPECIES_OCTILLERY,
};

const u16 gSeaPage5[] =
{
	SPECIES_SHELLDER,
	SPECIES_CLOYSTER,
};

const u16 gSeaPage6[] =
{
	SPECIES_CLAMPERL,
	SPECIES_HUNTAIL,
	SPECIES_GOREBYSS,
};

const u16 gSeaPage7[] =
{
	SPECIES_QWILFISH,
	SPECIES_CORSOLA,
	SPECIES_CORSOLA_G,
	SPECIES_CURSOLA,
};

const u16 gSeaPage8[] =
{
	SPECIES_SEEL,
	SPECIES_DEWGONG,
	SPECIES_MANTYKE,
	SPECIES_MANTINE,
};

const u16 gSeaPage9[] =
{
	SPECIES_SPHEAL,
	SPECIES_SEALEO,
	SPECIES_WALREIN,
};

const u16 gSeaPage10[] =
{
	SPECIES_CARVANHA,
	SPECIES_SHARPEDO,
	SPECIES_WAILMER,
	SPECIES_WAILORD,
};

const u16 gSeaPage11[] =
{
	SPECIES_HORSEA,
	SPECIES_SEADRA,
	SPECIES_KINGDRA,
};

const u16 gSeaPage12[] =
{
	SPECIES_LUVDISC,
	SPECIES_RELICANTH,
};

const u16 gSeaPage13[] =
{
	SPECIES_LAPRAS,
};

const u16 gSeaPage14[] =
{
	SPECIES_OMANYTE,
	SPECIES_OMASTAR,
	SPECIES_KABUTO,
	SPECIES_KABUTOPS,
};

const u16 gSeaPage15[] =
{
	SPECIES_LILEEP,
	SPECIES_CRADILY,
};

const u16 gSeaPage16[] =
{
	SPECIES_KYOGRE,
};

const u16 gSeaPage17[] =
{
	SPECIES_MANAPHY,
	SPECIES_PHIONE,
};

const u16 gSeaPage18[] =
{
	SPECIES_TIRTOUGA,
	SPECIES_CARRACOSTA,
	SPECIES_DRACOVISH,
	SPECIES_ARCTOVISH,
};

const u16 gSeaPage19[] =
{
	SPECIES_FRILLISH,
	SPECIES_JELLICENT,
	SPECIES_ALOMOMOLA,
	SPECIES_DHELMISE,
};

const u16 gSeaPage20[] =
{
	SPECIES_WISHIWASHI,
	SPECIES_WISHIWASHI_S,
};

const u16 gSeaPage21[] =
{
	SPECIES_MAREANIE,
	SPECIES_TOXAPEX,
	SPECIES_PYUKUMUKU,
};

const u16 gSeaPage22[] =
{
	SPECIES_CRAMORANT,
	SPECIES_CRAMORANT_GULPING,
	SPECIES_CRAMORANT_GORGING,
};

const u16 gSeaPage23[] =
{
	SPECIES_QWILFISH_H,
	SPECIES_OVERQWIL,
};

const u16 gCavePage1[] =
{
	SPECIES_ZUBAT,
	SPECIES_GOLBAT,
	SPECIES_CROBAT,
};

const u16 gCavePage2[] =
{
	SPECIES_DIGLETT,
	SPECIES_DUGTRIO,
	SPECIES_ONIX,
	SPECIES_STEELIX,
};

const u16 gCavePage3[] =
{
	SPECIES_DIGLETT_A,
	SPECIES_DUGTRIO_A,
};

const u16 gCavePage4[] =
{
	SPECIES_SWINUB,
	SPECIES_PILOSWINE,
	SPECIES_MAMOSWINE,
};

const u16 gCavePage5[] =
{
	SPECIES_SNORUNT,
	SPECIES_GLALIE,
	SPECIES_FROSLASS,
};

const u16 gCavePage6[] =
{
	SPECIES_WHISMUR,
	SPECIES_LOUDRED,
	SPECIES_EXPLOUD,
};

const u16 gCavePage7[] =
{
	SPECIES_MISDREAVUS,
	SPECIES_MISMAGIUS,
	SPECIES_DUNSPARCE,
};

const u16 gCavePage8[] =
{
	SPECIES_NOSEPASS,
	SPECIES_PROBOPASS,
};

const u16 gCavePage9[] =
{
	SPECIES_SABLEYE,
	SPECIES_MAWILE,
};

const u16 gCavePage10[] =
{
	SPECIES_GASTLY,
	SPECIES_HAUNTER,
	SPECIES_GENGAR,
};

const u16 gCavePage11[] =
{
	SPECIES_WYNAUT,
	SPECIES_WOBBUFFET,
};

const u16 gCavePage12[] =
{
	SPECIES_LUNATONE,
	SPECIES_SOLROCK,
};

const u16 gCavePage13[] =
{
	SPECIES_REGIROCK,
	SPECIES_REGICE,
	SPECIES_REGISTEEL,
};

const u16 gCavePage14[] =
{
	SPECIES_CRANIDOS,
	SPECIES_RAMPARDOS,
	SPECIES_SHIELDON,
	SPECIES_BASTIODON,
};

const u16 gCavePage15[] =
{
	SPECIES_BRONZOR,
	SPECIES_BRONZONG,
};

const u16 gCavePage16[] =
{
	SPECIES_GIBLE,
	SPECIES_GABITE,
	SPECIES_GARCHOMP,
};

const u16 gCavePage17[] =
{
	SPECIES_UXIE,
	SPECIES_MESPRIT,
	SPECIES_AZELF,
};

const u16 gCavePage18[] =
{
	SPECIES_HEATRAN,
	SPECIES_REGIGIGAS,
};

const u16 gCavePage19[] =
{
	SPECIES_ROGGENROLA,
	SPECIES_BOLDORE,
	SPECIES_GIGALITH,
};

const u16 gCavePage20[] =
{
	SPECIES_WOOBAT,
	SPECIES_SWOOBAT,
	SPECIES_DRILBUR,
	SPECIES_EXCADRILL,
};

const u16 gCavePage21[] =
{
	SPECIES_JOLTIK,
	SPECIES_GALVANTULA,
	SPECIES_FERROSEED,
	SPECIES_FERROTHORN,
};

const u16 gCavePage22[] =
{
	SPECIES_KLINK,
	SPECIES_KLANG,
	SPECIES_KLINKLANG,
};

const u16 gCavePage23[] =
{
	SPECIES_TYNAMO,
	SPECIES_EELEKTRIK,
	SPECIES_EELEKTROSS,
};

const u16 gCavePage24[] =
{
	SPECIES_AXEW,
	SPECIES_FRAXURE,
	SPECIES_HAXORUS,
};

const u16 gCavePage25[] =
{
	SPECIES_CUBCHOO,
	SPECIES_BEARTIC,
	SPECIES_CRYOGONAL,
};

const u16 gCavePage26[] =
{
	SPECIES_DEINO,
	SPECIES_ZWEILOUS,
	SPECIES_HYDREIGON,
};

const u16 gCavePage27[] =
{
	SPECIES_LARVESTA,
	SPECIES_VOLCARONA,
};

const u16 gCavePage28[] =
{
	SPECIES_COBALION,
	SPECIES_TERRAKION,
	SPECIES_VIRIZION,
};

const u16 gCavePage29[] =
{
	SPECIES_KELDEO,
	SPECIES_KELDEO_RESOLUTE,
};

const u16 gCavePage30[] =
{
	SPECIES_BERGMITE,
	SPECIES_AVALUGG,
	SPECIES_CARBINK,
	SPECIES_DIANCIE,
};

const u16 gCavePage31[] =
{
	SPECIES_ZYGARDE_10,
	SPECIES_ZYGARDE,
	SPECIES_ZYGARDE_COMPLETE,
};

const u16 gCavePage32[] =
{
	SPECIES_JANGMO_O,
	SPECIES_HAKAMO_O,
	SPECIES_KOMMO_O,
};

const u16 gCavePage33[] =
{
	SPECIES_TAPU_KOKO,
	SPECIES_TAPU_LELE,
	SPECIES_TAPU_BULU,
	SPECIES_TAPU_FINI,
};

const u16 gCavePage34[] =
{
	SPECIES_ROLYCOLY,
	SPECIES_CARKOL,
	SPECIES_COALOSSAL,
};

const u16 gCavePage35[] =
{
	SPECIES_REGIELEKI,
	SPECIES_REGIDRAGO,
};

const u16 gCavePage36[] =
{
	SPECIES_AVALUGG_H,
};

const u16 gMountainPage1[] =
{
	SPECIES_GEODUDE,
	SPECIES_GRAVELER,
	SPECIES_GOLEM,
};

const u16 gMountainPage2[] =
{
	SPECIES_GEODUDE_A,
	SPECIES_GRAVELER_A,
	SPECIES_GOLEM_A,
};

const u16 gMountainPage3[] =
{
	SPECIES_MANKEY,
	SPECIES_PRIMEAPE,
	SPECIES_SPOINK,
	SPECIES_GRUMPIG,
};

const u16 gMountainPage4[] =
{
	SPECIES_MACHOP,
	SPECIES_MACHOKE,
	SPECIES_MACHAMP,
};

const u16 gMountainPage5[] =
{
	SPECIES_CLEFFA,
	SPECIES_CLEFAIRY,
	SPECIES_CLEFABLE,
};

const u16 gMountainPage6[] =
{
	SPECIES_CUBONE,
	SPECIES_MAROWAK,
	SPECIES_MAROWAK_A,
};

const u16 gMountainPage7[] =
{
	SPECIES_ARTICUNO,
	SPECIES_ZAPDOS,
	SPECIES_MOLTRES,
};

const u16 gMountainPage8[] =
{
	SPECIES_ARTICUNO_G,
	SPECIES_ZAPDOS_G,
	SPECIES_MOLTRES_G,
};

const u16 gMountainPage9[] =
{
	SPECIES_SLUGMA,
	SPECIES_MAGCARGO,
	SPECIES_NUMEL,
	SPECIES_CAMERUPT,
};

const u16 gMountainPage10[] =
{
	SPECIES_MAKUHITA,
	SPECIES_HARIYAMA,
	SPECIES_MEDITITE,
	SPECIES_MEDICHAM,
};

const u16 gMountainPage11[] =
{
	SPECIES_SHUCKLE,
	SPECIES_TEDDIURSA,
	SPECIES_URSARING,
	SPECIES_URSALUNA,
};

const u16 gMountainPage12[] =
{
	SPECIES_DELIBIRD,
	SPECIES_GLIGAR,
	SPECIES_GLISCOR,
	SPECIES_SPINDA,
};

const u16 gMountainPage13[] =
{
	SPECIES_MAGBY,
	SPECIES_MAGMAR,
	SPECIES_MAGMORTAR,
	SPECIES_TORKOAL,
};

const u16 gMountainPage14[] =
{
	SPECIES_ARON,
	SPECIES_LAIRON,
	SPECIES_AGGRON,
};

const u16 gMountainPage15[] =
{
	SPECIES_LARVITAR,
	SPECIES_PUPITAR,
	SPECIES_TYRANITAR,
};

const u16 gMountainPage16[] =
{
	SPECIES_MUNCHLAX,
	SPECIES_SNORLAX,
};

const u16 gMountainPage17[] =
{
	SPECIES_VULPIX_A,
	SPECIES_NINETALES_A,
	SPECIES_ABSOL,
};

const u16 gMountainPage18[] =
{
	SPECIES_SANDSHREW_A,
	SPECIES_SANDSLASH_A,
	SPECIES_AERODACTYL,
};

const u16 gMountainPage19[] =
{
	SPECIES_MUNCHLAX,
	SPECIES_SNORLAX,
};

const u16 gMountainPage20[] =
{
	SPECIES_CHARMANDER,
	SPECIES_CHARMELEON,
	SPECIES_CHARIZARD,
};

const u16 gMountainPage21[] =
{
	SPECIES_JIRACHI,
};

const u16 gMountainPage22[] =
{
	SPECIES_RIOLU,
	SPECIES_LUCARIO,
	SPECIES_CROAGUNK,
	SPECIES_TOXICROAK,
};

const u16 gMountainPage23[] =
{
	SPECIES_CARNIVINE,
	SPECIES_SNOVER,
	SPECIES_ABOMASNOW,
};

const u16 gMountainPage24[] =
{
	SPECIES_TIMBURR,
	SPECIES_GURDURR,
	SPECIES_CONKELDURR,
};

const u16 gMountainPage25[] =
{
	SPECIES_THROH,
	SPECIES_SAWK,
};

const u16 gMountainPage26[] =
{
	SPECIES_ARCHEN,
	SPECIES_ARCHEOPS,
};

const u16 gMountainPage27[] =
{
	SPECIES_VANILLITE,
	SPECIES_VANILLISH,
	SPECIES_VANILLUXE,
};

const u16 gMountainPage28[] =
{
	SPECIES_MIENFOO,
	SPECIES_MIENSHAO,
	SPECIES_DRUDDIGON,
};

const u16 gMountainPage29[] =
{
	SPECIES_RUFFLET,
	SPECIES_BRAVIARY,
	SPECIES_BRAVIARY_H,
};

const u16 gMountainPage30[] =
{
	SPECIES_HEATMOR,
	SPECIES_DURANT,
	SPECIES_VULLABY,
	SPECIES_MANDIBUZZ,
};

const u16 gMountainPage31[] =
{
	SPECIES_INKAY,
	SPECIES_MALAMAR,
};

const u16 gMountainPage32[] =
{
	SPECIES_TYRUNT,
	SPECIES_TYRANTRUM,
	SPECIES_AMAURA,
	SPECIES_AURORUS,
};

const u16 gMountainPage33[] =
{
	SPECIES_NOIBAT,
	SPECIES_NOIVERN,
};

const u16 gMountainPage34[] =
{
	SPECIES_XERNEAS,
	SPECIES_YVELTAL,
};

const u16 gMountainPage35[] =
{
	SPECIES_CRABRAWLER,
	SPECIES_CRABOMINABLE,
};

const u16 gMountainPage36[] =
{
	SPECIES_ROCKRUFF,
	SPECIES_LYCANROC,
	SPECIES_LYCANROC_N,
	SPECIES_LYCANROC_DUSK,
};

const u16 gMountainPage37[] =
{
	SPECIES_SALANDIT,
	SPECIES_SALAZZLE,
};

const u16 gMountainPage38[] =
{
	SPECIES_TURTONATOR,
	SPECIES_TOGEDEMARU,
	SPECIES_DRAMPA,
};

const u16 gMountainPage39[]=
{
	SPECIES_MINIOR_SHIELD,
	SPECIES_MINIOR_RED,
	SPECIES_MINIOR_BLUE,
	SPECIES_MINIOR_ORANGE,
};

const u16 gMountainPage40[]=
{
	SPECIES_MINIOR_YELLOW,
	SPECIES_MINIOR_INDIGO,
	SPECIES_MINIOR_GREEN,
	SPECIES_MINIOR_VIOLET,
};

const u16 gMountainPage41[] =
{
	SPECIES_ZERAORA,
};

const u16 gMountainPage42[] =
{
	SPECIES_STONJOURNER,
	SPECIES_CUFANT,
	SPECIES_COPPERAJAH,
	SPECIES_DURALUDON,
};

const u16 gMountainPage43[] =
{
	SPECIES_SNOM,
	SPECIES_FROSMOTH,
};

const u16 gRoughTerrainPage1[] =
{
	SPECIES_SPEAROW,
	SPECIES_FEAROW,
};

const u16 gRoughTerrainPage2[] =
{
	SPECIES_SANDSHREW,
	SPECIES_SANDSLASH,
};

const u16 gRoughTerrainPage3[] =
{
	SPECIES_RHYHORN,
	SPECIES_RHYDON,
	SPECIES_RHYPERIOR,
};

const u16 gRoughTerrainPage4[] =
{
	SPECIES_MAGNEMITE,
	SPECIES_MAGNETON,
	SPECIES_MAGNEZONE,
};

const u16 gRoughTerrainPage5[] =
{
	SPECIES_HOUNDOUR,
	SPECIES_HOUNDOOM,
	SPECIES_PHANPY,
	SPECIES_DONPHAN,
};

const u16 gRoughTerrainPage6[] =
{
	SPECIES_CACNEA,
	SPECIES_CACTURNE,
};

const u16 gRoughTerrainPage7[] =
{
	SPECIES_TRAPINCH,
	SPECIES_VIBRAVA,
	SPECIES_FLYGON,
};

const u16 gRoughTerrainPage8[] =
{
	SPECIES_SKARMORY,
};

const u16 gRoughTerrainPage9[] =
{
	SPECIES_BALTOY,
	SPECIES_CLAYDOL,
};

const u16 gRoughTerrainPage10[] =
{
	SPECIES_BAGON,
	SPECIES_SHELGON,
	SPECIES_SALAMENCE,
};

const u16 gRoughTerrainPage11[] =
{
	SPECIES_BELDUM,
	SPECIES_METANG,
	SPECIES_METAGROSS,
};

const u16 gRoughTerrainPage12[] =
{
	SPECIES_GROUDON,
};

const u16 gRoughTerrainPage13[] =
{
	SPECIES_HIPPOPOTAS,
	SPECIES_HIPPOWDON,
};

const u16 gRoughTerrainPage14[] =
{
	SPECIES_SKORUPI,
	SPECIES_DRAPION,
};

const u16 gRoughTerrainPage15[] =
{
	SPECIES_SANDILE,
	SPECIES_KROKOROK,
	SPECIES_KROOKODILE,
};

const u16 gRoughTerrainPage16[] =
{
	SPECIES_MARACTUS,
	SPECIES_DARUMAKA,
	SPECIES_DARMANITAN,
	SPECIES_DARMANITANZEN,

};

const u16 gRoughTerrainPage17[] =
{
	SPECIES_DARUMAKA_G,
	SPECIES_DARMANITAN_G,
	SPECIES_DARMANITAN_G_ZEN,
};

const u16 gRoughTerrainPage18[] =
{
	SPECIES_SCRAGGY,
	SPECIES_SCRAFTY,
	SPECIES_DWEBBLE,
	SPECIES_CRUSTLE,
};

const u16 gRoughTerrainPage19[] =
{
	SPECIES_SIGILYPH,
	SPECIES_YAMASK,
	SPECIES_COFAGRIGUS,
};

const u16 gRoughTerrainPage20[] =
{
	SPECIES_YAMASK_G,
	SPECIES_RUNERIGUS,
};

const u16 gRoughTerrainPage21[] =
{
	SPECIES_GOLETT,
	SPECIES_GOLURK,
	SPECIES_PAWNIARD,
	SPECIES_BISHARP,
};

const u16 gRoughTerrainPage22[] =
{
	SPECIES_HONEDGE,
	SPECIES_DOUBLADE,
	SPECIES_AEGISLASH,
	SPECIES_AEGISLASH_BLADE,
};

const u16 gRoughTerrainPage23[] =
{
	SPECIES_HELIOPTILE,
	SPECIES_HELIOLISK,
};

const u16 gRoughTerrainPage24[] =
{
	SPECIES_HOOPA,
	SPECIES_HOOPA_UNBOUND,
	SPECIES_VOLCANION,
};

const u16 gRoughTerrainPage25[] =
{
	SPECIES_ROOKIDEE,
	SPECIES_CORVISQUIRE,
	SPECIES_CORVIKNIGHT,
};

const u16 gRoughTerrainPage26[] =
{
	SPECIES_MEOWTH_G,
	SPECIES_PERRSERKER,
	SPECIES_FALINKS,
};

const u16 gRoughTerrainPage27[] =
{
	SPECIES_SIZZLIPEDE,
	SPECIES_CENTISKORCH,
	SPECIES_SILICOBRA,
	SPECIES_SANDACONDA,
};

const u16 gRoughTerrainPage28[] =
{
	SPECIES_DRACOZOLT,
	SPECIES_ARCTOZOLT,
};

const u16 gUrbanPage1[] =
{
	SPECIES_MEOWTH,
	SPECIES_PERSIAN,
	SPECIES_SNUBBULL,
	SPECIES_GRANBULL,
};

const u16 gUrbanPage2[] =
{
	SPECIES_RATTATA_A,
	SPECIES_RATICATE_A,
	SPECIES_MEOWTH_A,
	SPECIES_PERSIAN_A,
};

const u16 gUrbanPage3[] =
{
	SPECIES_GRIMER,
	SPECIES_MUK,
	SPECIES_KOFFING,
	SPECIES_WEEZING,
};

const u16 gUrbanPage4[] =
{
	SPECIES_GRIMER_A,
	SPECIES_MUK_A,
	SPECIES_KOFFING_G,
	SPECIES_WEEZING_G,
};

const u16 gUrbanPage5[] =
{
	SPECIES_SHUPPET,
	SPECIES_BANETTE,
};

const u16 gUrbanPage6[] =
{
	SPECIES_ABRA,
	SPECIES_KADABRA,
	SPECIES_ALAKAZAM,
};

const u16 gUrbanPage7[] =
{
	SPECIES_RALTS,
	SPECIES_KIRLIA,
	SPECIES_GARDEVOIR,
	SPECIES_GALLADE,
};

const u16 gUrbanPage8[] =
{
	SPECIES_SMOOCHUM,
	SPECIES_JYNX,
	SPECIES_SMEARGLE,
};

const u16 gUrbanPage9[] =
{
	SPECIES_MIME_JR,
	SPECIES_MR_MIME,
};

const u16 gUrbanPage10[] =
{
	SPECIES_MIME_JR_G,
	SPECIES_MR_MIME_G,
	SPECIES_MR_RIME,
};

const u16 gUrbanPage11[] =
{
	SPECIES_TYROGUE,
	SPECIES_HITMONLEE,
	SPECIES_HITMONCHAN,
	SPECIES_HITMONTOP,
};

const u16 gUrbanPage12[] =
{
	SPECIES_HAPPINY,
	SPECIES_CHANSEY,
	SPECIES_BLISSEY,
};

const u16 gUrbanPage13[] =
{
	SPECIES_VOLTORB,
	SPECIES_ELECTRODE,
	SPECIES_VOLTORB_H,
	SPECIES_ELECTRODE_H,
};

const u16 gUrbanPage14[] =
{
	SPECIES_PORYGON,
	SPECIES_PORYGON2,
	SPECIES_PORYGON_Z,
};

const u16 gUrbanPage15[] =
{
	SPECIES_DITTO,
};

const u16 gUrbanPage16[] =
{
	SPECIES_EEVEE,
	SPECIES_VAPOREON,
	SPECIES_JOLTEON,
	SPECIES_FLAREON,
};

const u16 gUrbanPage17[] =
{
	SPECIES_ESPEON,
	SPECIES_UMBREON,
};

const u16 gUrbanPage18[] =
{
	SPECIES_LEAFEON,
	SPECIES_GLACEON,
	SPECIES_SYLVEON,
};

const u16 gUrbanPage19[] =
{
	SPECIES_ROTOM,
	SPECIES_ROTOM_HEAT,
	SPECIES_ROTOM_WASH,
};

const u16 gUrbanPage20[] =
{
	SPECIES_ROTOM_FROST,
	SPECIES_ROTOM_FAN,
	SPECIES_ROTOM_MOW,
};

const u16 gUrbanPage21[] =
{
	SPECIES_TEPIG,
	SPECIES_PIGNITE,
	SPECIES_EMBOAR,
};

const u16 gUrbanPage22[] =
{
	SPECIES_MUNNA,
	SPECIES_MUSHARNA,
	SPECIES_AUDINO,
};

const u16 gUrbanPage23[] =
{
	SPECIES_PIDOVE,
	SPECIES_TRANQUILL,
	SPECIES_UNFEZANT,
};

const u16 gUrbanPage24[] =
{
	SPECIES_TRUBBISH,
	SPECIES_GARBODOR,
};

const u16 gUrbanPage25[] =
{
	SPECIES_GOTHITA,
	SPECIES_GOTHORITA,
	SPECIES_GOTHITELLE,
};

const u16 gUrbanPage26[] =
{
	SPECIES_SOLOSIS,
	SPECIES_DUOSION,
	SPECIES_REUNICLUS,
};

const u16 gUrbanPage27[] =
{
	SPECIES_ELGYEM,
	SPECIES_BEHEEYEM,
};

const u16 gUrbanPage28[] =
{
	SPECIES_LITWICK,
	SPECIES_LAMPENT,
	SPECIES_CHANDELURE,
};

const u16 gUrbanPage29[] =
{
	SPECIES_FENNEKIN,
	SPECIES_BRAIXEN,
	SPECIES_DELPHOX,
};

const u16 gUrbanPage30[] =
{
	SPECIES_KLEFKI,
	SPECIES_MIMIKYU,
	SPECIES_MIMIKYU_BUSTED,
};

const u16 gUrbanPage31[] =
{
	SPECIES_LITTEN,
	SPECIES_TORRACAT,
	SPECIES_INCINEROAR,
};

const u16 gUrbanPage32[] =
{
	SPECIES_SCORBUNNY,
	SPECIES_RABOOT,
	SPECIES_CINDERACE,
};

const u16 gUrbanPage33[] =
{
	SPECIES_TOXEL,
	SPECIES_TOXTRICITY,
	SPECIES_TOXTRICITY_LOW_KEY,
};

const u16 gUrbanPage34[] =
{
	SPECIES_SINISTEA,
	SPECIES_POLTEAGEIST,
	SPECIES_SINISTEA_CHIPPED,
	SPECIES_POLTEAGEIST_CHIPPED,
};

const u16 gUrbanPage35[] =
{
	SPECIES_MILCERY,
	SPECIES_ALCREMIE_STRAWBERRY,
};

const u16 gUrbanPage36[] =
{
	SPECIES_ALCREMIE_BERRY,
	SPECIES_ALCREMIE_CLOVER,
	SPECIES_ALCREMIE_FLOWER,
};

const u16 gUrbanPage37[] =
{
	SPECIES_ALCREMIE_LOVE,
	SPECIES_ALCREMIE_RIBBON,
	SPECIES_ALCREMIE_STAR,
};

const u16 gRarePage1[] =
{
	SPECIES_UNOWN,
};

const u16 gRarePage2[] =
{
	SPECIES_LUGIA,
	SPECIES_HO_OH,
	SPECIES_LUGIA_S,
};

const u16 gRarePage3[] =
{
	SPECIES_RAYQUAZA,
};

const u16 gRarePage4[] =
{
	SPECIES_DEOXYS,
	SPECIES_DEOXYS_ATTACK,
	SPECIES_DEOXYS_DEFENSE,
	SPECIES_DEOXYS_SPEED,
};

const u16 gRarePage5[] =
{
	SPECIES_MEWTWO,
	SPECIES_MEW,
};

const u16 gRarePage6[] =
{
	SPECIES_SPIRITOMB,
};

const u16 gRarePage7[] =
{
	SPECIES_DIALGA,
	SPECIES_PALKIA,
	SPECIES_GIRATINA,
	SPECIES_GIRATINA_ORIGIN,
};

const u16 gRarePage8[] =
{
	SPECIES_ARCEUS,
	SPECIES_ARCEUS_FIRE,
	SPECIES_ARCEUS_WATER,
	SPECIES_ARCEUS_GRASS,
};

const u16 gRarePage9[] =
{
	SPECIES_ARCEUS_ELECTRIC,
	SPECIES_ARCEUS_ICE,
	SPECIES_ARCEUS_FIGHT,
	SPECIES_ARCEUS_POISON,
};

const u16 gRarePage10[] =
{
	SPECIES_ARCEUS_GROUND,
	SPECIES_ARCEUS_FLYING,
	SPECIES_ARCEUS_PSYCHIC,
	SPECIES_ARCEUS_BUG,
};

const u16 gRarePage11[] =
{
	SPECIES_ARCEUS_ROCK,
	SPECIES_ARCEUS_GHOST,
	SPECIES_ARCEUS_DRAGON,
};

const u16 gRarePage12[] =
{
	SPECIES_ARCEUS_DARK,
	SPECIES_ARCEUS_STEEL,
	SPECIES_ARCEUS_FAIRY,
};

const u16 gRarePage13[] =
{
	SPECIES_VICTINI,
};

const u16 gRarePage14[] =
{
	SPECIES_TORNADUS,
	SPECIES_THUNDURUS,
	SPECIES_LANDORUS,
	SPECIES_ENAMORUS,
};

const u16 gRarePage15[] =
{
	SPECIES_TORNADUS_THERIAN,
	SPECIES_THUNDURUS_THERIAN,
	SPECIES_LANDORUS_THERIAN,
	SPECIES_ENAMORUS_T,
};

const u16 gRarePage16[] =
{
	SPECIES_RESHIRAM,
	SPECIES_ZEKROM,
};

const u16 gRarePage17[] =
{
	SPECIES_KYUREM,
	SPECIES_KYUREM_BLACK,
	SPECIES_KYUREM_WHITE,
};

const u16 gRarePage18[] =
{
	SPECIES_MELOETTA,
	SPECIES_MELOETTA_PIROUETTE,
	SPECIES_GENESECT,
};

const u16 gRarePage19[] =
{
	SPECIES_GENESECT_SHOCK,
	SPECIES_GENESECT_BURN,
	SPECIES_GENESECT_CHILL,
	SPECIES_GENESECT_DOUSE,
};

const u16 gRarePage20[] =
{
	SPECIES_TYPE_NULL,
	SPECIES_SILVALLY,
	SPECIES_SILVALLY_FIGHT,
	SPECIES_SILVALLY_FLYING,
};

const u16 gRarePage21[] =
{
	SPECIES_SILVALLY_POISON,
	SPECIES_SILVALLY_GROUND,
	SPECIES_SILVALLY_ROCK,
	SPECIES_SILVALLY_BUG,
};

const u16 gRarePage22[] =
{
	SPECIES_SILVALLY_GHOST,
	SPECIES_SILVALLY_STEEL,
	SPECIES_SILVALLY_FIRE,
	SPECIES_SILVALLY_WATER,
};

const u16 gRarePage23[] =
{
	SPECIES_SILVALLY_GRASS,
	SPECIES_SILVALLY_ELECTRIC,
	SPECIES_SILVALLY_PSYCHIC,
	SPECIES_SILVALLY_ICE,
};

const u16 gRarePage24[] =
{
	SPECIES_SILVALLY_DRAGON,
	SPECIES_SILVALLY_DARK,
	SPECIES_SILVALLY_FAIRY,
};

const u16 gRarePage25[] =
{
	SPECIES_COSMOG,
	SPECIES_COSMOEM,
	SPECIES_SOLGALEO,
	SPECIES_LUNALA,
};

const u16 gRarePage26[] =
{
	SPECIES_NIHILEGO,
	SPECIES_BUZZWOLE,
	SPECIES_PHEROMOSA,
	SPECIES_XURKITREE,
};

const u16 gRarePage27[] =
{
	SPECIES_CELESTEELA,
	SPECIES_KARTANA,
	SPECIES_GUZZLORD,
};

const u16 gRarePage28[] =
{
	SPECIES_NECROZMA,
	SPECIES_NECROZMA_DUSK_MANE,
	SPECIES_NECROZMA_DAWN_WINGS,
	SPECIES_NECROZMA_ULTRA,
};

const u16 gRarePage29[] =
{
	SPECIES_MAGEARNA,
	SPECIES_MAGEARNA_P,
	SPECIES_MARSHADOW,
};

const u16 gRarePage30[] =
{
	SPECIES_POIPOLE,
	SPECIES_NAGANADEL,
	SPECIES_STAKATAKA,
	SPECIES_BLACEPHALON,
};

const u16 gRarePage31[] =
{
	SPECIES_MELTAN,
	SPECIES_MELMETAL,
};

const u16 gRarePage32[] =
{
	SPECIES_ZACIAN,
	SPECIES_ZACIAN_CROWNED,
	SPECIES_ZAMAZENTA,
	SPECIES_ZAMAZENTA_CROWNED,
};

const u16 gRarePage33[] =
{
	SPECIES_ETERNATUS,
	SPECIES_ETERNATUS_ETERNAMAX,
};

const u16 gRarePage34[] =
{
	SPECIES_KUBFU,
	SPECIES_URSHIFU_SINGLE,
	SPECIES_URSHIFU_RAPID,
};

const u16 gRarePage35[] =
{
	SPECIES_ZARUDE,
	SPECIES_ZARUDE_DADA,
};

const u16 gRarePage36[] =
{
	SPECIES_GLASTRIER,
	SPECIES_SPECTRIER,
};

const u16 gRarePage37[] =
{
	SPECIES_CALYREX,
	SPECIES_CALYREX_ICE_RIDER,
	SPECIES_CALYREX_SHADOW_RIDER,
};

const u16 gRarePage38[] =
{
	SPECIES_S1,
	SPECIES_S2,
	SPECIES_S3,
	SPECIES_S4,
};

const u16 gRarePage39[] =
{
	SPECIES_S5,
	SPECIES_S6,
	SPECIES_S7,
	SPECIES_S8,
};

const u16 gRarePage40[] =
{
	SPECIES_S9,
	SPECIES_S10,
	SPECIES_S11,
	SPECIES_S12,
};

const u16 gRarePage41[] =
{
	SPECIES_S13,
	SPECIES_S14,
	SPECIES_S15,
	SPECIES_S16,
};

const u16 gRarePage42[] =
{
	SPECIES_S17,
	SPECIES_S18,
	SPECIES_S19,
	SPECIES_S20,
};

const u16 gRarePage43[] =
{
	SPECIES_S21,
	SPECIES_S22,
	SPECIES_S23,
	SPECIES_S24,
};

const u16 gRarePage44[] =
{
	SPECIES_S25,
	SPECIES_S26,
	SPECIES_S27,
	SPECIES_S28,
};

const u16 gRarePage45[] =
{
	SPECIES_S29,
	SPECIES_S30,
	SPECIES_S31,
	SPECIES_S32,
};

const u16 gRarePage46[] =
{
	SPECIES_S33,
	SPECIES_S34,
	SPECIES_S35,
	SPECIES_S36,
};

const u16 gRarePage47[] =
{
	SPECIES_S37,
	SPECIES_S38,
	SPECIES_S39,
	SPECIES_S40,
};

const u16 gRarePage48[] =
{
	SPECIES_S41,
	SPECIES_S42,
	SPECIES_S43,
	SPECIES_S44,
};

const u16 gRarePage49[] =
{
	SPECIES_S45,
	SPECIES_S46,
	SPECIES_S47,
	SPECIES_S48,
};

const u16 gRarePage50[] =
{
	SPECIES_S49,
	SPECIES_S50,
	SPECIES_S51,
	SPECIES_S52,
};

const u16 gRarePage51[] =
{
	SPECIES_S53,
	SPECIES_S54,
	SPECIES_S55,
	SPECIES_S56,
};

const u16 gRarePage52[] =
{
	SPECIES_S57,
	SPECIES_S58,
	SPECIES_S59,
	SPECIES_S60,
};

const u16 gRarePage53[] =
{
	SPECIES_S61,
	SPECIES_S62,
	SPECIES_S63,
	SPECIES_S64,
};

const u16 gRarePage54[] =
{
	SPECIES_S65,
	SPECIES_S66,
	SPECIES_S67,
	SPECIES_S68,
};

const u16 gRarePage55[] =
{
	SPECIES_S69,
	SPECIES_S70,
	SPECIES_S71,
	SPECIES_S72,
};

const u16 gRarePage56[] =
{
	SPECIES_S73,
	SPECIES_S74,
	SPECIES_S75,
	SPECIES_S76,
};

const u16 gRarePage57[] =
{
	SPECIES_S77,
	SPECIES_S78,
	SPECIES_S79,
	SPECIES_S80,
};

const u16 gRarePage58[] =
{
	SPECIES_S81,
	SPECIES_S82,
	SPECIES_S83,
	SPECIES_S84,
};

const u16 gRarePage59[] =
{
	SPECIES_S85,
	SPECIES_S86,
	SPECIES_S87,
	SPECIES_S88,
};

const u16 gRarePage60[] =
{
	SPECIES_S89,
	SPECIES_S90,
	SPECIES_S91,
	SPECIES_S92,
};

const u16 gRarePage61[] =
{
	SPECIES_S93,
	SPECIES_S94,
	SPECIES_S95,
	SPECIES_S96,
};

const u16 gRarePage62[] =
{
	SPECIES_S97,
	SPECIES_S98,
	SPECIES_S99,
	SPECIES_S100,
};

const u16 gRarePage63[] =
{
	SPECIES_S101,
	SPECIES_S102,
	SPECIES_S103,
	SPECIES_S104,
};

const u16 gRarePage64[] =
{
	SPECIES_S105,
	SPECIES_S106,
	SPECIES_S107,
	SPECIES_S108,
};

const u16 gRarePage65[] =
{
	SPECIES_S109,
	SPECIES_S110,
	SPECIES_S111,
	SPECIES_S112,
};

const u16 gRarePage66[] =
{
	SPECIES_S113,
	SPECIES_S114,
	SPECIES_S115,
	SPECIES_S116,
};

const u16 gRarePage67[] =
{
	SPECIES_S117,
	SPECIES_S118,
	SPECIES_S119,
	SPECIES_S120,
};

const u16 gRarePage68[] =
{
	SPECIES_S121,
	SPECIES_S122,
	SPECIES_S123,
	SPECIES_S124,
};

const u16 gRarePage69[] =
{
	SPECIES_S125,
	SPECIES_S126,
	SPECIES_S127,
	SPECIES_S128,
};

const u16 gRarePage70[] =
{
	SPECIES_S129,
	SPECIES_S130,
	SPECIES_S131,
	SPECIES_S132,
};

const u16 gRarePage71[] =
{
	SPECIES_S133,
	SPECIES_S134,
	SPECIES_S135,
	SPECIES_S136,
};

const u16 gRarePage72[] =
{
	SPECIES_S137,
	SPECIES_S138,
	SPECIES_S139,
	SPECIES_S140,
};

const u16 gRarePage73[] =
{
	SPECIES_S141,
	SPECIES_S142,
	SPECIES_S143,
	SPECIES_S144,
};

const u16 gRarePage74[] =
{
	SPECIES_S145,
	SPECIES_S146,
	SPECIES_S147,
	SPECIES_S148,
};

const u16 gRarePage75[] =
{
	SPECIES_S149,
	SPECIES_S150,
	SPECIES_S151,
	SPECIES_S152,
};

const u16 gRarePage76[] =
{
	SPECIES_S153,
	SPECIES_S154,
	SPECIES_S155,
	SPECIES_S156,
};

const u16 gRarePage77[] =
{
	SPECIES_S157,
	SPECIES_S158,
	SPECIES_S159,
	SPECIES_S160,
};

const u16 gRarePage78[] =
{
	SPECIES_S161,
	SPECIES_S162,
	SPECIES_S163,
	SPECIES_S164,
};

const u16 gRarePage79[] =
{
	SPECIES_S165,
	SPECIES_S166,
	SPECIES_S167,
	SPECIES_S167,
};

const u16 gRarePage80[] =
{
	SPECIES_S168,
	SPECIES_S169,
	SPECIES_S170,
	SPECIES_S171,
};

const u16 gRarePage81[] =
{
	SPECIES_S172,
	SPECIES_S173,
	SPECIES_S174,
	SPECIES_S175,
};

const u16 gRarePage82[] =
{
	SPECIES_S176,
	SPECIES_S177,
	SPECIES_S178,
	SPECIES_S179,
};

const u16 gRarePage83[] =
{
	SPECIES_S180,
	SPECIES_S181,
	SPECIES_S182,
	SPECIES_S183,
};

const u16 gRarePage84[] =
{
	SPECIES_S184,
	SPECIES_S185,
	SPECIES_S186,
	SPECIES_S187,
};

const u16 gRarePage85[] =
{
	SPECIES_S188,
	SPECIES_S189,
	SPECIES_S190,
	SPECIES_S191,
};

const u16 gRarePage86[] =
{
	SPECIES_S192,
	SPECIES_S193,
	SPECIES_S194,
	SPECIES_S195,
};

const u16 gRarePage87[] =
{
	SPECIES_S196,
	SPECIES_S197,
	SPECIES_S198,
	SPECIES_S199,
};

const u16 gRarePage88[] =
{
	SPECIES_S200,
	SPECIES_S201,
	SPECIES_S202,
	SPECIES_S203,
};

const u16 gRarePage89[] =
{
	SPECIES_S204,
	SPECIES_S205,
	SPECIES_S206,
	SPECIES_S207,
};

const u16 gRarePage90[] =
{
	SPECIES_S208,
	SPECIES_S209,
	SPECIES_S210,
	SPECIES_S211,
};

const u16 gRarePage91[] =
{
	SPECIES_S212,
	SPECIES_S213,
	SPECIES_S214,
	SPECIES_S215,
};

const u16 gRarePage92[] =
{
	SPECIES_S216,
	SPECIES_S217,
	SPECIES_S218,
	SPECIES_S219,
};

const u16 gRarePage93[] =
{
	SPECIES_S220,
	SPECIES_S221,
	SPECIES_S222,
	SPECIES_S223,
};

const u16 gRarePage94[] =
{
	SPECIES_S224,
	SPECIES_S225,
	SPECIES_S226,
	SPECIES_S227,
};

const u16 gRarePage95[] =
{
	SPECIES_S228,
	SPECIES_S229,
	SPECIES_S230,
	SPECIES_S231,
};

const u16 gRarePage96[] =
{
	SPECIES_S232,
	SPECIES_S233,
	SPECIES_S234,
	SPECIES_S235,
};

const u16 gRarePage97[] =
{
	SPECIES_S236,
	SPECIES_S237,
	SPECIES_S238,
	SPECIES_S239,
};

const u16 gRarePage98[] =
{
	SPECIES_S240,
	SPECIES_S241,
	SPECIES_S242,
	SPECIES_S243,
};

const u16 gRarePage99[] =
{
	SPECIES_S243,
	SPECIES_S244,
	SPECIES_S245,
	SPECIES_S246,
};

const u16 gRarePage100[] =
{
	SPECIES_S247,
	SPECIES_S248,
	SPECIES_S249,
	SPECIES_S250,
};

const u16 gRarePage101[] =
{
	SPECIES_S251,
	SPECIES_S252,
	SPECIES_S253,
	SPECIES_S254,
};

const u16 gRarePage102[] =
{
	SPECIES_S255,
	SPECIES_S256,
	SPECIES_S257,
	SPECIES_S258,
};

const u16 gRarePage103[] =
{
	SPECIES_S259,
	SPECIES_S260,
	SPECIES_S261,
	SPECIES_S262,
};

const u16 gRarePage104[] =
{
	SPECIES_S263,
	SPECIES_S264,
	SPECIES_S265,
	SPECIES_S266,
};

const u16 gRarePage105[] =
{
	SPECIES_S267,
	SPECIES_S268,
	SPECIES_S269,
	SPECIES_S270,
};

const u16 gRarePage106[] =
{
	SPECIES_S271,
	SPECIES_S272,
	SPECIES_S273,
	SPECIES_S274,
};

const u16 gRarePage107[] =
{
	SPECIES_S275,
	SPECIES_S276,
	SPECIES_S277,
	SPECIES_S278,
};

const u16 gRarePage108[] =
{
	SPECIES_S279,
	SPECIES_S280,
	SPECIES_S281,
	SPECIES_S282,
};

const u16 gRarePage109[] =
{
	SPECIES_S283,
	SPECIES_S284,
	SPECIES_S285,
	SPECIES_S286,
};

const u16 gRarePage110[] =
{
	SPECIES_S287,
	SPECIES_S288,
	SPECIES_S289,
	SPECIES_S290,
};

const u16 gRarePage111[] =
{
	SPECIES_S290,
	SPECIES_S291,
	SPECIES_S292,
	SPECIES_S293,
};

const u16 gRarePage112[] =
{
	SPECIES_S294,
	SPECIES_S295,
	SPECIES_S296,
	SPECIES_S297,
};

const u16 gRarePage113[] =
{
	SPECIES_S298,
	SPECIES_S299,
	SPECIES_S300,
	SPECIES_S301,
};

const u16 gRarePage114[] =
{
	SPECIES_S302,
	SPECIES_S303,
	SPECIES_S304,
	SPECIES_S305,
};

const u16 gRarePage115[] =
{
	SPECIES_S306,
	SPECIES_S307,
	SPECIES_S308,
	SPECIES_S309,
};

const u16 gRarePage116[] =
{
	SPECIES_S310,
	SPECIES_S311,
	SPECIES_S312,
	SPECIES_S313,
};

const u16 gRarePage117[] =
{
	SPECIES_S314,
	SPECIES_S315,
	SPECIES_S316,
	SPECIES_S317,
};

const u16 gRarePage118[] =
{
	SPECIES_S318,
	SPECIES_S319,
	SPECIES_S320,
	SPECIES_S321,
};

const u16 gRarePage119[] =
{
	SPECIES_S322,
	SPECIES_S323,
	SPECIES_S324,
	SPECIES_S325,
};

const u16 gRarePage120[] =
{
	SPECIES_S326,
	SPECIES_S327,
	SPECIES_S328,
	SPECIES_S329,
};

const u16 gRarePage121[] =
{
	SPECIES_S330,
	SPECIES_S331,
	SPECIES_S332,
	SPECIES_S333,
};

const u16 gRarePage122[] =
{
	SPECIES_S334,
	SPECIES_S335,
	SPECIES_S336,
	SPECIES_S337,
};

const u16 gRarePage123[] =
{
	SPECIES_S338,
	SPECIES_S339,
	SPECIES_S340,
	SPECIES_S341,
};

const u16 gRarePage124[] =
{
	SPECIES_S342,
	SPECIES_S343,
	SPECIES_S344,
	SPECIES_S345,
};

const u16 gRarePage125[] =
{
	SPECIES_S346,
	SPECIES_S347,
	SPECIES_S348,
	SPECIES_S349,
};

const u16 gRarePage126[] =
{
	SPECIES_S350,
	SPECIES_S351,
	SPECIES_S352,
	SPECIES_S353,
};

const u16 gRarePage127[] =
{
	SPECIES_S354,
	SPECIES_S355,
	SPECIES_S356,
	SPECIES_S357,
};

const u16 gRarePage128[] =
{
	SPECIES_S358,
	SPECIES_S359,
	SPECIES_S360,
	SPECIES_S361,
};

const u16 gRarePage129[] =
{
	SPECIES_S362,
	SPECIES_S363,
	SPECIES_S364,
	SPECIES_S365,
};

const u16 gRarePage130[] =
{
	SPECIES_S366,
	SPECIES_S367,
	SPECIES_S368,
	SPECIES_S369,
};

const u16 gRarePage131[] =
{
	SPECIES_S370,
	SPECIES_S371,
	SPECIES_S372,
	SPECIES_S373,
};

const u16 gRarePage132[] =
{
	SPECIES_S377,
	SPECIES_S378,
	SPECIES_S379,
	SPECIES_S380,
};

const u16 gRarePage133[] =
{
	SPECIES_S381,
	SPECIES_S382,
	SPECIES_S383,
	SPECIES_S384,
};

const u16 gRarePage134[] =
{
	SPECIES_S385,
	SPECIES_S386,
	SPECIES_S387,
	SPECIES_S388,
};

const u16 gRarePage135[] =
{
	SPECIES_S389,
	SPECIES_S390,
	SPECIES_S391,
	SPECIES_S392,
};

const u16 gRarePage136[] =
{
	SPECIES_S393,
	SPECIES_S394,
	SPECIES_S395,
	SPECIES_S396,
};

const u16 gRarePage137[] =
{
	SPECIES_S397,
	SPECIES_S398,
	SPECIES_S399,
	SPECIES_S400,
};

const u16 gRarePage138[] =
{
	SPECIES_S401,
	SPECIES_S402,
	SPECIES_S403,
	SPECIES_S404,
};

const u16 gRarePage139[] =
{
	SPECIES_S405,
	SPECIES_S406,
	SPECIES_S407,
	SPECIES_S408,
};

const u16 gRarePage140[] =
{
	SPECIES_S409,
	SPECIES_S410,
	SPECIES_S411,
	SPECIES_S412,
};

const u16 gRarePage141[] =
{
	SPECIES_S413,
	SPECIES_S414,
	SPECIES_S415,
	SPECIES_S416,
};

const u16 gRarePage142[] =
{
	SPECIES_S417,
	SPECIES_S418,
	SPECIES_S419,
	SPECIES_S420,
};

const u16 gRarePage143[] =
{
	SPECIES_S421,
	SPECIES_S422,
	SPECIES_S423,
	SPECIES_S424,
};

const u16 gRarePage144[] =
{
	SPECIES_S425,
	SPECIES_S426,
	SPECIES_S427,
	SPECIES_S428,
};

const u16 gRarePage145[] =
{
	SPECIES_S429,
	SPECIES_S430,
	SPECIES_S431,
	SPECIES_S432,
};

const u16 gRarePage146[] =
{
	SPECIES_S433,
	SPECIES_S434,
	SPECIES_S435,
	SPECIES_S436,
};

const u16 gRarePage147[] =
{
	SPECIES_S437,
	SPECIES_S438,
	SPECIES_S439,
	SPECIES_S440,
};

const u16 gRarePage148[] =
{
	SPECIES_S441,
	SPECIES_S442,
	SPECIES_S443,
	SPECIES_S444,
};

const u16 gRarePage149[] =
{
	SPECIES_S445,
	SPECIES_S446,
	SPECIES_S447,
	SPECIES_S448,
};

const u16 gRarePage150[] =
{
	SPECIES_S449,
	SPECIES_S450,
	SPECIES_S451,
	SPECIES_S452,
};

const u16 gRarePage151[] =
{
	SPECIES_S453,
	SPECIES_S454,
	SPECIES_S455,
	SPECIES_S456,
};

const u16 gRarePage152[] =
{
	SPECIES_S457,
	SPECIES_S458,
	SPECIES_S459,
	SPECIES_S460,
};

const u16 gRarePage153[] =
{
	SPECIES_S461,
	SPECIES_S462,
	SPECIES_S463,
	SPECIES_S464,
};

const u16 gRarePage154[] =
{
	SPECIES_S465,
	SPECIES_S466,
	SPECIES_S467,
	SPECIES_S467,
};

const u16 gRarePage155[] =
{
	SPECIES_S468,
	SPECIES_S469,
	SPECIES_S470,
	SPECIES_S471,
};

const u16 gRarePage156[] =
{
	SPECIES_S472,
	SPECIES_S473,
	SPECIES_S474,
	SPECIES_S475,
};

const u16 gRarePage157[] =
{
	SPECIES_S476,
	SPECIES_S477,
	SPECIES_S478,
	SPECIES_S479,
};

const u16 gRarePage158[] =
{
	SPECIES_S480,
	SPECIES_S481,
	SPECIES_S482,
	SPECIES_S483,
};

const u16 gRarePage159[] =
{
	SPECIES_S484,
	SPECIES_S485,
	SPECIES_S486,
	SPECIES_S487,
};

const u16 gRarePage160[] =
{
	SPECIES_S488,
	SPECIES_S489,
	SPECIES_S490,
	SPECIES_S491,
};

const u16 gRarePage161[] =
{
	SPECIES_S492,
	SPECIES_S493,
	SPECIES_S494,
	SPECIES_S495,
};

const u16 gRarePage162[] =
{
	SPECIES_S496,
	SPECIES_S497,
	SPECIES_S498,
	SPECIES_S499,
};

const u16 gRarePage163[] =
{
	SPECIES_S500,
	SPECIES_S501,
	SPECIES_S502,
	SPECIES_S503,
};

const u16 gRarePage164[] =
{
	SPECIES_S504,
	SPECIES_S505,
	SPECIES_S506,
	SPECIES_S507,
};

const u16 gRarePage165[] =
{
	SPECIES_S508,
	SPECIES_S509,
	SPECIES_S510,
	SPECIES_S511,
};

const u16 gRarePage166[] =
{
	SPECIES_S512,
	SPECIES_S513,
	SPECIES_S514,
	SPECIES_S515,
};

const u16 gRarePage167[] =
{
	SPECIES_S516,
	SPECIES_S517,
	SPECIES_S518,
	SPECIES_S519,
};

const u16 gRarePage168[] =
{
	SPECIES_S520,
	SPECIES_S521,
	SPECIES_S522,
	SPECIES_S523,
};

const u16 gRarePage169[] =
{
	SPECIES_S524,
	SPECIES_S525,
	SPECIES_S526,
	SPECIES_S527,
};

const u16 gRarePage170[] =
{
	SPECIES_S528,
	SPECIES_S529,
	SPECIES_S530,
	SPECIES_S531,
};

const u16 gRarePage171[] =
{
	SPECIES_S532,
	SPECIES_S533,
	SPECIES_S534,
	SPECIES_S535,
};

const u16 gRarePage172[] =
{
	SPECIES_S536,
	SPECIES_S537,
	SPECIES_S538,
	SPECIES_S539,
};

const u16 gRarePage173[] =
{
	SPECIES_S540,
	SPECIES_S541,
	SPECIES_S542,
	SPECIES_S543,
};

const u16 gRarePage174[] =
{
	SPECIES_S543,
	SPECIES_S544,
	SPECIES_S545,
	SPECIES_S546,
};

const u16 gRarePage175[] =
{
	SPECIES_S547,
	SPECIES_S548,
	SPECIES_S549,
	SPECIES_S550,
};

const u16 gRarePage176[] =
{
	SPECIES_S551,
	SPECIES_S552,
	SPECIES_S553,
	SPECIES_S554,
};

const u16 gRarePage177[] =
{
	SPECIES_S555,
	SPECIES_S556,
	SPECIES_S557,
	SPECIES_S558,
};

const u16 gRarePage178[] =
{
	SPECIES_S559,
	SPECIES_S560,
	SPECIES_S561,
	SPECIES_S562,
};

const u16 gRarePage179[] =
{
	SPECIES_S563,
	SPECIES_S564,
	SPECIES_S565,
	SPECIES_S566,
};

const u16 gRarePage180[] =
{
	SPECIES_S567,
	SPECIES_S568,
	SPECIES_S569,
	SPECIES_S570,
};

const u16 gRarePage181[] =
{
	SPECIES_S571,
	SPECIES_S572,
	SPECIES_S573,
	SPECIES_S574,
};

const u16 gRarePage182[] =
{
	SPECIES_S575,
	SPECIES_S576,
	SPECIES_S577,
	SPECIES_S578,
};

const u16 gRarePage183[] =
{
	SPECIES_S579,
	SPECIES_S580,
	SPECIES_S581,
	SPECIES_S582,
};

const u16 gRarePage184[] =
{
	SPECIES_S583,
	SPECIES_S584,
	SPECIES_S585,
	SPECIES_S586,
};

const u16 gRarePage185[] =
{
	SPECIES_S587,
	SPECIES_S588,
	SPECIES_S589,
	SPECIES_S590,
};

const u16 gRarePage186[] =
{
	SPECIES_S590,
	SPECIES_S591,
	SPECIES_S592,
	SPECIES_S593,
};

const u16 gRarePage187[] =
{
	SPECIES_S594,
	SPECIES_S595,
	SPECIES_S596,
	SPECIES_S597,
};

const u16 gRarePage188[] =
{
	SPECIES_S598,
	SPECIES_S599,
	SPECIES_S600,
	SPECIES_S601,
};

const u16 gRarePage189[] =
{
	SPECIES_S602,
	SPECIES_S603,
	SPECIES_S604,
	SPECIES_S605,
};

const u16 gRarePage190[] =
{
	SPECIES_S606,
	SPECIES_S607,
	SPECIES_S608,
	SPECIES_S609,
};

const u16 gRarePage191[] =
{
	SPECIES_S610,
	SPECIES_S611,
	SPECIES_S612,
	SPECIES_S613,
};

const u16 gRarePage192[] =
{
	SPECIES_S614,
	SPECIES_S615,
	SPECIES_S616,
	SPECIES_S617,
};

const u16 gRarePage193[] =
{
	SPECIES_S618,
	SPECIES_S619,
	SPECIES_S620,
	SPECIES_S621,
};

const u16 gRarePage194[] =
{
	SPECIES_S622,
	SPECIES_S623,
	SPECIES_S624,
	SPECIES_S625,
};

const u16 gRarePage195[] =
{
	SPECIES_S626,
	SPECIES_S627,
	SPECIES_S628,
	SPECIES_S629,
};

const u16 gRarePage196[] =
{
	SPECIES_S630,
	SPECIES_S631,
	SPECIES_S632,
	SPECIES_S633,
};

const u16 gRarePage197[] =
{
	SPECIES_S634,
	SPECIES_S635,
	SPECIES_S636,
	SPECIES_S637,
};

const u16 gRarePage198[] =
{
	SPECIES_S638,
	SPECIES_S639,
	SPECIES_S640,
	SPECIES_S641,
};

const u16 gRarePage199[] =
{
	SPECIES_S642,
	SPECIES_S643,
	SPECIES_S644,
	SPECIES_S645,
};

const u16 gRarePage200[] =
{
	SPECIES_S646,
	SPECIES_S647,
	SPECIES_S648,
	SPECIES_S649,
};

const u16 gRarePage201[] =
{
	SPECIES_S650,
	SPECIES_S651,
	SPECIES_S652,
	SPECIES_S653,
};

const u16 gRarePage202[] =
{
	SPECIES_S654,
	SPECIES_S655,
	SPECIES_S656,
	SPECIES_S657,
};

const u16 gRarePage203[] =
{
	SPECIES_S658,
	SPECIES_S659,
	SPECIES_S660,
	SPECIES_S661,
};

const u16 gRarePage204[] =
{
	SPECIES_S662,
	SPECIES_S663,
	SPECIES_S664,
	SPECIES_S665,
};

const u16 gRarePage205[] =
{
	SPECIES_S666,
	SPECIES_S667,
	SPECIES_S668,
	SPECIES_S669,
};

const u16 gRarePage206[] =
{
	SPECIES_S670,
	SPECIES_S671,
	SPECIES_S672,
	SPECIES_S673,
};

const u16 gRarePage207[] =
{
	SPECIES_S677,
	SPECIES_S678,
	SPECIES_S679,
	SPECIES_S680,
};

const u16 gRarePage208[] =
{
	SPECIES_S681,
	SPECIES_S682,
	SPECIES_S683,
	SPECIES_S684,
};

const u16 gRarePage209[] =
{
	SPECIES_S685,
	SPECIES_S686,
	SPECIES_S687,
	SPECIES_S688,
};

const u16 gRarePage210[] =
{
	SPECIES_S689,
	SPECIES_S690,
	SPECIES_S691,
	SPECIES_S692,
};

const u16 gRarePage211[] =
{
	SPECIES_S693,
	SPECIES_S694,
	SPECIES_S695,
	SPECIES_S696,
};

const u16 gRarePage212[] =
{
	SPECIES_S697,
	SPECIES_S698,
	SPECIES_S699,
	SPECIES_S700,
};

const u16 gRarePage213[] =
{
	SPECIES_S701,
	SPECIES_S702,
	SPECIES_S703,
	SPECIES_S704,
};

const u16 gRarePage214[] =
{
	SPECIES_S705,
	SPECIES_S706,
	SPECIES_S707,
	SPECIES_S708,
};

const u16 gRarePage215[] =
{
	SPECIES_S709,
	SPECIES_S710,
	SPECIES_S711,
	SPECIES_S712,
};

const u16 gRarePage216[] =
{
	SPECIES_S713,
	SPECIES_S714,
	SPECIES_S715,
	SPECIES_S716,
};

const u16 gRarePage217[] =
{
	SPECIES_S717,
	SPECIES_S718,
	SPECIES_S719,
	SPECIES_S720,
};

const u16 gRarePage218[] =
{
	SPECIES_S721,
	SPECIES_S722,
	SPECIES_S723,
	SPECIES_S724,
};

const u16 gRarePage219[] =
{
	SPECIES_S725,
	SPECIES_S726,
	SPECIES_S727,
	SPECIES_S728,
};

const u16 gRarePage220[] =
{
	SPECIES_S729,
	SPECIES_S730,
	SPECIES_S731,
	SPECIES_S732,
};

const u16 gRarePage221[] =
{
	SPECIES_S733,
	SPECIES_S734,
	SPECIES_S735,
	SPECIES_S736,
};

const u16 gRarePage222[] =
{
	SPECIES_S737,
	SPECIES_S738,
	SPECIES_S739,
	SPECIES_S740,
};

const u16 gRarePage223[] =
{
	SPECIES_S741,
	SPECIES_S742,
	SPECIES_S743,
	SPECIES_S744,
};

const u16 gRarePage224[] =
{
	SPECIES_S745,
	SPECIES_S746,
	SPECIES_S747,
	SPECIES_S748,
};

const u16 gRarePage225[] =
{
	SPECIES_S749,
	SPECIES_S750,
	SPECIES_S751,
	SPECIES_S752,
};

const u16 gRarePage226[] =
{
	SPECIES_S753,
	SPECIES_S754,
	SPECIES_S755,
	SPECIES_S756,
};

const u16 gRarePage227[] =
{
	SPECIES_S757,
	SPECIES_S758,
	SPECIES_S759,
	SPECIES_S760,
};

const u16 gRarePage228[] =
{
	SPECIES_S761,
	SPECIES_S762,
	SPECIES_S763,
	SPECIES_S764,
};

const u16 gRarePage229[] =
{
	SPECIES_S765,
	SPECIES_S766,
	SPECIES_S767,
	SPECIES_S767,
};

const u16 gRarePage230[] =
{
	SPECIES_S768,
	SPECIES_S769,
	SPECIES_S770,
	SPECIES_S771,
};

const u16 gRarePage231[] =
{
	SPECIES_S772,
	SPECIES_S773,
	SPECIES_S774,
	SPECIES_S775,
};

const u16 gRarePage232[] =
{
	SPECIES_S776,
	SPECIES_S777,
	SPECIES_S778,
	SPECIES_S779,
};

const u16 gRarePage233[] =
{
	SPECIES_S780,
	SPECIES_S781,
	SPECIES_S782,
	SPECIES_S783,
};

const u16 gRarePage234[] =
{
	SPECIES_S784,
	SPECIES_S785,
	SPECIES_S786,
	SPECIES_S787,
};

const u16 gRarePage235[] =
{
	SPECIES_S788,
	SPECIES_S789,
	SPECIES_S790,
	SPECIES_S791,
};

const u16 gRarePage236[] =
{
	SPECIES_S792,
	SPECIES_S793,
	SPECIES_S794,
	SPECIES_S795,
};

const u16 gRarePage237[] =
{
	SPECIES_S796,
	SPECIES_S797,
	SPECIES_S798,
	SPECIES_S799,
};

const u16 gRarePage238[] =
{
	SPECIES_S800,
};

const struct HabitatPage gGrasslandPages[] =
{
	{gGrasslandPage1, ARRAY_COUNT(gGrasslandPage1)}, 
	{gGrasslandPage2, ARRAY_COUNT(gGrasslandPage2)}, 
	{gGrasslandPage3, ARRAY_COUNT(gGrasslandPage3)}, 
	{gGrasslandPage4, ARRAY_COUNT(gGrasslandPage4)}, 
	{gGrasslandPage5, ARRAY_COUNT(gGrasslandPage5)}, 
	{gGrasslandPage6, ARRAY_COUNT(gGrasslandPage6)}, 
	{gGrasslandPage7, ARRAY_COUNT(gGrasslandPage7)}, 
	{gGrasslandPage8, ARRAY_COUNT(gGrasslandPage8)}, 
	{gGrasslandPage9, ARRAY_COUNT(gGrasslandPage9)}, 
	{gGrasslandPage10, ARRAY_COUNT(gGrasslandPage10)}, 
	{gGrasslandPage11, ARRAY_COUNT(gGrasslandPage11)}, 
	{gGrasslandPage12, ARRAY_COUNT(gGrasslandPage12)}, 
	{gGrasslandPage13, ARRAY_COUNT(gGrasslandPage13)}, 
	{gGrasslandPage14, ARRAY_COUNT(gGrasslandPage14)}, 
	{gGrasslandPage15, ARRAY_COUNT(gGrasslandPage15)}, 
	{gGrasslandPage16, ARRAY_COUNT(gGrasslandPage16)}, 
	{gGrasslandPage17, ARRAY_COUNT(gGrasslandPage17)}, 
	{gGrasslandPage18, ARRAY_COUNT(gGrasslandPage18)}, 
	{gGrasslandPage19, ARRAY_COUNT(gGrasslandPage19)}, 
	{gGrasslandPage20, ARRAY_COUNT(gGrasslandPage20)}, 
	{gGrasslandPage21, ARRAY_COUNT(gGrasslandPage21)}, 
	{gGrasslandPage22, ARRAY_COUNT(gGrasslandPage22)}, 
	{gGrasslandPage23, ARRAY_COUNT(gGrasslandPage23)}, 
	{gGrasslandPage24, ARRAY_COUNT(gGrasslandPage24)}, 
	{gGrasslandPage25, ARRAY_COUNT(gGrasslandPage25)}, 
	{gGrasslandPage26, ARRAY_COUNT(gGrasslandPage26)}, 
	{gGrasslandPage27, ARRAY_COUNT(gGrasslandPage27)}, 
	{gGrasslandPage28, ARRAY_COUNT(gGrasslandPage28)}, 
	{gGrasslandPage29, ARRAY_COUNT(gGrasslandPage29)}, 
	{gGrasslandPage30, ARRAY_COUNT(gGrasslandPage30)}, 
	{gGrasslandPage31, ARRAY_COUNT(gGrasslandPage31)}, 
	{gGrasslandPage32, ARRAY_COUNT(gGrasslandPage32)}, 
	{gGrasslandPage33, ARRAY_COUNT(gGrasslandPage33)}, 
	{gGrasslandPage34, ARRAY_COUNT(gGrasslandPage34)}, 
	{gGrasslandPage35, ARRAY_COUNT(gGrasslandPage35)}, 
	{gGrasslandPage36, ARRAY_COUNT(gGrasslandPage36)}, 
	{gGrasslandPage37, ARRAY_COUNT(gGrasslandPage37)}, 
	{gGrasslandPage38, ARRAY_COUNT(gGrasslandPage38)}, 
	{gGrasslandPage39, ARRAY_COUNT(gGrasslandPage39)}, 
	{gGrasslandPage40, ARRAY_COUNT(gGrasslandPage40)}, 
	{gGrasslandPage41, ARRAY_COUNT(gGrasslandPage41)}, 
	{gGrasslandPage42, ARRAY_COUNT(gGrasslandPage42)}, 
	{gGrasslandPage43, ARRAY_COUNT(gGrasslandPage43)}, 
	{gGrasslandPage44, ARRAY_COUNT(gGrasslandPage44)}, 
	{gGrasslandPage45, ARRAY_COUNT(gGrasslandPage45)}, 
	{gGrasslandPage46, ARRAY_COUNT(gGrasslandPage46)}, 
	{gGrasslandPage47, ARRAY_COUNT(gGrasslandPage47)}, 
	{gGrasslandPage48, ARRAY_COUNT(gGrasslandPage48)}, 
	{gGrasslandPage49, ARRAY_COUNT(gGrasslandPage49)}, 
	{gGrasslandPage50, ARRAY_COUNT(gGrasslandPage50)}, 
	{gGrasslandPage51, ARRAY_COUNT(gGrasslandPage51)}, 
	{gGrasslandPage52, ARRAY_COUNT(gGrasslandPage52)}, 
	{gGrasslandPage53, ARRAY_COUNT(gGrasslandPage53)}, 
	{gGrasslandPage54, ARRAY_COUNT(gGrasslandPage54)}, 
	{gGrasslandPage55, ARRAY_COUNT(gGrasslandPage55)}, 
	{gGrasslandPage56, ARRAY_COUNT(gGrasslandPage56)}, 
	{gGrasslandPage57, ARRAY_COUNT(gGrasslandPage57)}, 
	{gGrasslandPage58, ARRAY_COUNT(gGrasslandPage58)},
	{gGrasslandPage59, ARRAY_COUNT(gGrasslandPage59)},
};

const struct HabitatPage gForestPages[] =
{
	{gForestPage1, ARRAY_COUNT(gForestPage1)}, 
	{gForestPage2, ARRAY_COUNT(gForestPage2)}, 
	{gForestPage3, ARRAY_COUNT(gForestPage3)}, 
	{gForestPage4, ARRAY_COUNT(gForestPage4)}, 
	{gForestPage5, ARRAY_COUNT(gForestPage5)}, 
	{gForestPage6, ARRAY_COUNT(gForestPage6)}, 
	{gForestPage7, ARRAY_COUNT(gForestPage7)}, 
	{gForestPage8, ARRAY_COUNT(gForestPage8)}, 
	{gForestPage8_1, ARRAY_COUNT(gForestPage8_1)}, 
	{gForestPage8_2, ARRAY_COUNT(gForestPage8_2)}, 
	{gForestPage8_3, ARRAY_COUNT(gForestPage8_3)}, 
	{gForestPage8_4, ARRAY_COUNT(gForestPage8_4)}, 
	{gForestPage8_5, ARRAY_COUNT(gForestPage8_5)}, 
	{gForestPage9, ARRAY_COUNT(gForestPage9)}, 
	{gForestPage10, ARRAY_COUNT(gForestPage10)}, 
	{gForestPage11, ARRAY_COUNT(gForestPage11)}, 
	{gForestPage12, ARRAY_COUNT(gForestPage12)}, 
	{gForestPage13, ARRAY_COUNT(gForestPage13)}, 
	{gForestPage14, ARRAY_COUNT(gForestPage14)}, 
	{gForestPage15, ARRAY_COUNT(gForestPage15)}, 
	{gForestPage16, ARRAY_COUNT(gForestPage16)}, 
	{gForestPage17, ARRAY_COUNT(gForestPage17)}, 
	{gForestPage18, ARRAY_COUNT(gForestPage18)}, 
	{gForestPage19, ARRAY_COUNT(gForestPage19)}, 
	{gForestPage20, ARRAY_COUNT(gForestPage20)}, 
	{gForestPage21, ARRAY_COUNT(gForestPage21)}, 
	{gForestPage22, ARRAY_COUNT(gForestPage22)}, 
	{gForestPage23, ARRAY_COUNT(gForestPage23)}, 
	{gForestPage24, ARRAY_COUNT(gForestPage24)}, 
	{gForestPage25, ARRAY_COUNT(gForestPage25)}, 
	{gForestPage26, ARRAY_COUNT(gForestPage26)}, 
	{gForestPage27, ARRAY_COUNT(gForestPage27)}, 
	{gForestPage28, ARRAY_COUNT(gForestPage28)}, 
	{gForestPage29, ARRAY_COUNT(gForestPage29)}, 
	{gForestPage30, ARRAY_COUNT(gForestPage30)}, 
	{gForestPage31, ARRAY_COUNT(gForestPage31)}, 
	{gForestPage32, ARRAY_COUNT(gForestPage32)}, 
	{gForestPage33, ARRAY_COUNT(gForestPage33)}, 
	{gForestPage34, ARRAY_COUNT(gForestPage34)}, 
	{gForestPage35, ARRAY_COUNT(gForestPage35)}, 
	{gForestPage36, ARRAY_COUNT(gForestPage36)}, 
	{gForestPage37, ARRAY_COUNT(gForestPage37)}, 
	{gForestPage38, ARRAY_COUNT(gForestPage38)}, 
	{gForestPage39, ARRAY_COUNT(gForestPage39)}, 
	{gForestPage40, ARRAY_COUNT(gForestPage40)}, 
	{gForestPage41, ARRAY_COUNT(gForestPage41)}, 
	{gForestPage42, ARRAY_COUNT(gForestPage42)}, 
	{gForestPage43, ARRAY_COUNT(gForestPage43)}, 
	{gForestPage44, ARRAY_COUNT(gForestPage44)}, 
	{gForestPage45, ARRAY_COUNT(gForestPage45)}, 
	{gForestPage46, ARRAY_COUNT(gForestPage46)}, 
	{gForestPage47, ARRAY_COUNT(gForestPage47)}, 
	{gForestPage48, ARRAY_COUNT(gForestPage48)}, 
	{gForestPage49, ARRAY_COUNT(gForestPage49)}, 
	{gForestPage50, ARRAY_COUNT(gForestPage50)}, 
	{gForestPage51, ARRAY_COUNT(gForestPage51)}, 
	{gForestPage52, ARRAY_COUNT(gForestPage52)}, 
	{gForestPage53, ARRAY_COUNT(gForestPage53)}, 
	{gForestPage54, ARRAY_COUNT(gForestPage54)}, 
	{gForestPage55, ARRAY_COUNT(gForestPage55)}, 
	{gForestPage56, ARRAY_COUNT(gForestPage56)}, 
	{gForestPage57, ARRAY_COUNT(gForestPage57)}, 
	{gForestPage58, ARRAY_COUNT(gForestPage58)}, 
	{gForestPage59, ARRAY_COUNT(gForestPage59)},
	{gForestPage60, ARRAY_COUNT(gForestPage60)},
	{gForestPage61, ARRAY_COUNT(gForestPage61)},
	{gForestPage62, ARRAY_COUNT(gForestPage62)},
	{gForestPage63, ARRAY_COUNT(gForestPage63)},
	{gForestPage64, ARRAY_COUNT(gForestPage64)},
	{gForestPage65, ARRAY_COUNT(gForestPage65)},
	{gForestPage66, ARRAY_COUNT(gForestPage66)},
	{gForestPage67, ARRAY_COUNT(gForestPage67)},
};

const struct HabitatPage gWatersEdgePages[] =
{
	{gWatersEdgePage1, ARRAY_COUNT(gWatersEdgePage1)}, 
	{gWatersEdgePage2, ARRAY_COUNT(gWatersEdgePage2)}, 
	{gWatersEdgePage3, ARRAY_COUNT(gWatersEdgePage3)}, 
	{gWatersEdgePage4, ARRAY_COUNT(gWatersEdgePage4)}, 
	{gWatersEdgePage5, ARRAY_COUNT(gWatersEdgePage5)}, 
	{gWatersEdgePage6, ARRAY_COUNT(gWatersEdgePage6)}, 
	{gWatersEdgePage7, ARRAY_COUNT(gWatersEdgePage7)}, 
	{gWatersEdgePage8, ARRAY_COUNT(gWatersEdgePage8)}, 
	{gWatersEdgePage9, ARRAY_COUNT(gWatersEdgePage9)}, 
	{gWatersEdgePage10, ARRAY_COUNT(gWatersEdgePage10)}, 
	{gWatersEdgePage11, ARRAY_COUNT(gWatersEdgePage11)}, 
	{gWatersEdgePage12, ARRAY_COUNT(gWatersEdgePage12)}, 
	{gWatersEdgePage13, ARRAY_COUNT(gWatersEdgePage13)}, 
	{gWatersEdgePage14, ARRAY_COUNT(gWatersEdgePage14)}, 
	{gWatersEdgePage15, ARRAY_COUNT(gWatersEdgePage15)}, 
	{gWatersEdgePage16, ARRAY_COUNT(gWatersEdgePage16)}, 
	{gWatersEdgePage17, ARRAY_COUNT(gWatersEdgePage17)}, 
	{gWatersEdgePage18, ARRAY_COUNT(gWatersEdgePage18)}, 
	{gWatersEdgePage19, ARRAY_COUNT(gWatersEdgePage19)}, 
	{gWatersEdgePage20, ARRAY_COUNT(gWatersEdgePage20)}, 
	{gWatersEdgePage21, ARRAY_COUNT(gWatersEdgePage21)}, 
	{gWatersEdgePage22, ARRAY_COUNT(gWatersEdgePage22)}, 
	{gWatersEdgePage23, ARRAY_COUNT(gWatersEdgePage23)}, 
	{gWatersEdgePage24, ARRAY_COUNT(gWatersEdgePage24)}, 
	{gWatersEdgePage25, ARRAY_COUNT(gWatersEdgePage25)}, 
	{gWatersEdgePage26, ARRAY_COUNT(gWatersEdgePage26)}, 
	{gWatersEdgePage27, ARRAY_COUNT(gWatersEdgePage27)}, 
	{gWatersEdgePage28, ARRAY_COUNT(gWatersEdgePage28)}, 
	{gWatersEdgePage29, ARRAY_COUNT(gWatersEdgePage29)}, 
	{gWatersEdgePage30, ARRAY_COUNT(gWatersEdgePage30)}, 
	{gWatersEdgePage31, ARRAY_COUNT(gWatersEdgePage31)}, 
	{gWatersEdgePage32, ARRAY_COUNT(gWatersEdgePage32)}, 
	{gWatersEdgePage33, ARRAY_COUNT(gWatersEdgePage33)}, 
	{gWatersEdgePage34, ARRAY_COUNT(gWatersEdgePage34)}, 
	{gWatersEdgePage35, ARRAY_COUNT(gWatersEdgePage35)}, 
	{gWatersEdgePage36, ARRAY_COUNT(gWatersEdgePage36)},
	{gWatersEdgePage37, ARRAY_COUNT(gWatersEdgePage37)}, 
	{gWatersEdgePage38, ARRAY_COUNT(gWatersEdgePage38)}, 
	{gWatersEdgePage39, ARRAY_COUNT(gWatersEdgePage39)}, 
};

const struct HabitatPage gSeaPages[] =
{
	{gSeaPage1, ARRAY_COUNT(gSeaPage1)}, 
	{gSeaPage2, ARRAY_COUNT(gSeaPage2)}, 
	{gSeaPage3, ARRAY_COUNT(gSeaPage3)}, 
	{gSeaPage4, ARRAY_COUNT(gSeaPage4)}, 
	{gSeaPage5, ARRAY_COUNT(gSeaPage5)}, 
	{gSeaPage6, ARRAY_COUNT(gSeaPage6)}, 
	{gSeaPage7, ARRAY_COUNT(gSeaPage7)}, 
	{gSeaPage8, ARRAY_COUNT(gSeaPage8)}, 
	{gSeaPage9, ARRAY_COUNT(gSeaPage9)}, 
	{gSeaPage10, ARRAY_COUNT(gSeaPage10)}, 
	{gSeaPage11, ARRAY_COUNT(gSeaPage11)}, 
	{gSeaPage12, ARRAY_COUNT(gSeaPage12)}, 
	{gSeaPage13, ARRAY_COUNT(gSeaPage13)}, 
	{gSeaPage14, ARRAY_COUNT(gSeaPage14)}, 
	{gSeaPage15, ARRAY_COUNT(gSeaPage15)}, 
	{gSeaPage16, ARRAY_COUNT(gSeaPage16)}, 
	{gSeaPage17, ARRAY_COUNT(gSeaPage17)}, 
	{gSeaPage18, ARRAY_COUNT(gSeaPage18)}, 
	{gSeaPage19, ARRAY_COUNT(gSeaPage19)}, 
	{gSeaPage20, ARRAY_COUNT(gSeaPage20)}, 
	{gSeaPage21, ARRAY_COUNT(gSeaPage21)}, 
	{gSeaPage22, ARRAY_COUNT(gSeaPage22)}, 
	{gSeaPage23, ARRAY_COUNT(gSeaPage23)},
};

const struct HabitatPage gCavePages[] =
{
	{gCavePage1, ARRAY_COUNT(gCavePage1)}, 
	{gCavePage2, ARRAY_COUNT(gCavePage2)}, 
	{gCavePage3, ARRAY_COUNT(gCavePage3)}, 
	{gCavePage4, ARRAY_COUNT(gCavePage4)}, 
	{gCavePage5, ARRAY_COUNT(gCavePage5)}, 
	{gCavePage6, ARRAY_COUNT(gCavePage6)}, 
	{gCavePage7, ARRAY_COUNT(gCavePage7)}, 
	{gCavePage8, ARRAY_COUNT(gCavePage8)}, 
	{gCavePage9, ARRAY_COUNT(gCavePage9)}, 
	{gCavePage10, ARRAY_COUNT(gCavePage10)}, 
	{gCavePage11, ARRAY_COUNT(gCavePage11)}, 
	{gCavePage12, ARRAY_COUNT(gCavePage12)}, 
	{gCavePage13, ARRAY_COUNT(gCavePage13)}, 
	{gCavePage14, ARRAY_COUNT(gCavePage14)}, 
	{gCavePage15, ARRAY_COUNT(gCavePage15)}, 
	{gCavePage16, ARRAY_COUNT(gCavePage16)}, 
	{gCavePage17, ARRAY_COUNT(gCavePage17)}, 
	{gCavePage18, ARRAY_COUNT(gCavePage18)}, 
	{gCavePage19, ARRAY_COUNT(gCavePage19)}, 
	{gCavePage20, ARRAY_COUNT(gCavePage20)}, 
	{gCavePage21, ARRAY_COUNT(gCavePage21)}, 
	{gCavePage22, ARRAY_COUNT(gCavePage22)}, 
	{gCavePage23, ARRAY_COUNT(gCavePage23)}, 
	{gCavePage24, ARRAY_COUNT(gCavePage24)}, 
	{gCavePage25, ARRAY_COUNT(gCavePage25)}, 
	{gCavePage26, ARRAY_COUNT(gCavePage26)}, 
	{gCavePage27, ARRAY_COUNT(gCavePage27)}, 
	{gCavePage28, ARRAY_COUNT(gCavePage28)}, 
	{gCavePage29, ARRAY_COUNT(gCavePage29)}, 
	{gCavePage30, ARRAY_COUNT(gCavePage30)}, 
	{gCavePage31, ARRAY_COUNT(gCavePage31)}, 
	{gCavePage32, ARRAY_COUNT(gCavePage32)}, 
	{gCavePage33, ARRAY_COUNT(gCavePage33)}, 
	{gCavePage34, ARRAY_COUNT(gCavePage34)}, 
	{gCavePage35, ARRAY_COUNT(gCavePage35)}, 
	{gCavePage36, ARRAY_COUNT(gCavePage35)},
};

const struct HabitatPage gMountainPages[] =
{
	{gMountainPage1, ARRAY_COUNT(gMountainPage1)}, 
	{gMountainPage2, ARRAY_COUNT(gMountainPage2)}, 
	{gMountainPage3, ARRAY_COUNT(gMountainPage3)}, 
	{gMountainPage4, ARRAY_COUNT(gMountainPage4)}, 
	{gMountainPage5, ARRAY_COUNT(gMountainPage5)}, 
	{gMountainPage6, ARRAY_COUNT(gMountainPage6)}, 
	{gMountainPage7, ARRAY_COUNT(gMountainPage7)}, 
	{gMountainPage8, ARRAY_COUNT(gMountainPage8)}, 
	{gMountainPage9, ARRAY_COUNT(gMountainPage9)}, 
	{gMountainPage10, ARRAY_COUNT(gMountainPage10)}, 
	{gMountainPage11, ARRAY_COUNT(gMountainPage11)}, 
	{gMountainPage12, ARRAY_COUNT(gMountainPage12)}, 
	{gMountainPage13, ARRAY_COUNT(gMountainPage13)}, 
	{gMountainPage14, ARRAY_COUNT(gMountainPage14)}, 
	{gMountainPage15, ARRAY_COUNT(gMountainPage15)}, 
	{gMountainPage16, ARRAY_COUNT(gMountainPage16)}, 
	{gMountainPage17, ARRAY_COUNT(gMountainPage17)}, 
	{gMountainPage18, ARRAY_COUNT(gMountainPage18)}, 
	{gMountainPage19, ARRAY_COUNT(gMountainPage19)}, 
	{gMountainPage20, ARRAY_COUNT(gMountainPage20)}, 
	{gMountainPage21, ARRAY_COUNT(gMountainPage21)}, 
	{gMountainPage22, ARRAY_COUNT(gMountainPage22)}, 
	{gMountainPage23, ARRAY_COUNT(gMountainPage23)}, 
	{gMountainPage24, ARRAY_COUNT(gMountainPage24)}, 
	{gMountainPage25, ARRAY_COUNT(gMountainPage25)}, 
	{gMountainPage26, ARRAY_COUNT(gMountainPage26)}, 
	{gMountainPage27, ARRAY_COUNT(gMountainPage27)}, 
	{gMountainPage28, ARRAY_COUNT(gMountainPage28)}, 
	{gMountainPage29, ARRAY_COUNT(gMountainPage29)}, 
	{gMountainPage30, ARRAY_COUNT(gMountainPage30)}, 
	{gMountainPage31, ARRAY_COUNT(gMountainPage31)}, 
	{gMountainPage32, ARRAY_COUNT(gMountainPage32)}, 
	{gMountainPage33, ARRAY_COUNT(gMountainPage33)}, 
	{gMountainPage34, ARRAY_COUNT(gMountainPage34)}, 
	{gMountainPage35, ARRAY_COUNT(gMountainPage35)}, 
	{gMountainPage36, ARRAY_COUNT(gMountainPage36)},
	{gMountainPage37, ARRAY_COUNT(gMountainPage37)},
	{gMountainPage38, ARRAY_COUNT(gMountainPage38)},
	{gMountainPage39, ARRAY_COUNT(gMountainPage39)},
	{gMountainPage40, ARRAY_COUNT(gMountainPage40)},
	{gMountainPage41, ARRAY_COUNT(gMountainPage41)},
	{gMountainPage42, ARRAY_COUNT(gMountainPage42)},
	{gMountainPage43, ARRAY_COUNT(gMountainPage43)},
};

const struct HabitatPage gRoughTerrainPages[] =
{
	{gRoughTerrainPage1, ARRAY_COUNT(gRoughTerrainPage1)}, 
	{gRoughTerrainPage2, ARRAY_COUNT(gRoughTerrainPage2)}, 
	{gRoughTerrainPage3, ARRAY_COUNT(gRoughTerrainPage3)}, 
	{gRoughTerrainPage4, ARRAY_COUNT(gRoughTerrainPage4)}, 
	{gRoughTerrainPage5, ARRAY_COUNT(gRoughTerrainPage5)}, 
	{gRoughTerrainPage6, ARRAY_COUNT(gRoughTerrainPage6)}, 
	{gRoughTerrainPage7, ARRAY_COUNT(gRoughTerrainPage7)}, 
	{gRoughTerrainPage8, ARRAY_COUNT(gRoughTerrainPage8)}, 
	{gRoughTerrainPage9, ARRAY_COUNT(gRoughTerrainPage9)}, 
	{gRoughTerrainPage10, ARRAY_COUNT(gRoughTerrainPage10)}, 
	{gRoughTerrainPage11, ARRAY_COUNT(gRoughTerrainPage11)}, 
	{gRoughTerrainPage12, ARRAY_COUNT(gRoughTerrainPage12)}, 
	{gRoughTerrainPage13, ARRAY_COUNT(gRoughTerrainPage13)}, 
	{gRoughTerrainPage14, ARRAY_COUNT(gRoughTerrainPage14)}, 
	{gRoughTerrainPage15, ARRAY_COUNT(gRoughTerrainPage15)}, 
	{gRoughTerrainPage16, ARRAY_COUNT(gRoughTerrainPage16)}, 
	{gRoughTerrainPage17, ARRAY_COUNT(gRoughTerrainPage17)}, 
	{gRoughTerrainPage18, ARRAY_COUNT(gRoughTerrainPage18)}, 
	{gRoughTerrainPage19, ARRAY_COUNT(gRoughTerrainPage19)}, 
	{gRoughTerrainPage20, ARRAY_COUNT(gRoughTerrainPage20)}, 
	{gRoughTerrainPage21, ARRAY_COUNT(gRoughTerrainPage21)}, 
	{gRoughTerrainPage22, ARRAY_COUNT(gRoughTerrainPage22)}, 
	{gRoughTerrainPage23, ARRAY_COUNT(gRoughTerrainPage23)}, 
	{gRoughTerrainPage24, ARRAY_COUNT(gRoughTerrainPage24)}, 
	{gRoughTerrainPage25, ARRAY_COUNT(gRoughTerrainPage25)}, 
	{gRoughTerrainPage26, ARRAY_COUNT(gRoughTerrainPage26)}, 
	{gRoughTerrainPage27, ARRAY_COUNT(gRoughTerrainPage27)}, 
	{gRoughTerrainPage28, ARRAY_COUNT(gRoughTerrainPage28)}, 
};

const struct HabitatPage gUrbanPages[] =
{
	{gUrbanPage1, ARRAY_COUNT(gUrbanPage1)}, 
	{gUrbanPage2, ARRAY_COUNT(gUrbanPage2)}, 
	{gUrbanPage3, ARRAY_COUNT(gUrbanPage3)}, 
	{gUrbanPage4, ARRAY_COUNT(gUrbanPage4)}, 
	{gUrbanPage5, ARRAY_COUNT(gUrbanPage5)}, 
	{gUrbanPage6, ARRAY_COUNT(gUrbanPage6)}, 
	{gUrbanPage7, ARRAY_COUNT(gUrbanPage7)}, 
	{gUrbanPage8, ARRAY_COUNT(gUrbanPage8)}, 
	{gUrbanPage9, ARRAY_COUNT(gUrbanPage9)}, 
	{gUrbanPage10, ARRAY_COUNT(gUrbanPage10)}, 
	{gUrbanPage11, ARRAY_COUNT(gUrbanPage11)}, 
	{gUrbanPage12, ARRAY_COUNT(gUrbanPage12)}, 
	{gUrbanPage13, ARRAY_COUNT(gUrbanPage13)}, 
	{gUrbanPage14, ARRAY_COUNT(gUrbanPage14)}, 
	{gUrbanPage15, ARRAY_COUNT(gUrbanPage15)}, 
	{gUrbanPage16, ARRAY_COUNT(gUrbanPage16)}, 
	{gUrbanPage17, ARRAY_COUNT(gUrbanPage17)}, 
	{gUrbanPage18, ARRAY_COUNT(gUrbanPage18)}, 
	{gUrbanPage19, ARRAY_COUNT(gUrbanPage19)}, 
	{gUrbanPage20, ARRAY_COUNT(gUrbanPage20)}, 
	{gUrbanPage21, ARRAY_COUNT(gUrbanPage21)}, 
	{gUrbanPage22, ARRAY_COUNT(gUrbanPage22)}, 
	{gUrbanPage23, ARRAY_COUNT(gUrbanPage23)}, 
	{gUrbanPage24, ARRAY_COUNT(gUrbanPage24)}, 
	{gUrbanPage25, ARRAY_COUNT(gUrbanPage25)}, 
	{gUrbanPage26, ARRAY_COUNT(gUrbanPage26)}, 
	{gUrbanPage27, ARRAY_COUNT(gUrbanPage27)}, 
	{gUrbanPage28, ARRAY_COUNT(gUrbanPage28)}, 
	{gUrbanPage29, ARRAY_COUNT(gUrbanPage29)}, 
	{gUrbanPage30, ARRAY_COUNT(gUrbanPage30)}, 
	{gUrbanPage31, ARRAY_COUNT(gUrbanPage31)}, 
	{gUrbanPage32, ARRAY_COUNT(gUrbanPage32)}, 
	{gUrbanPage33, ARRAY_COUNT(gUrbanPage33)}, 
	{gUrbanPage34, ARRAY_COUNT(gUrbanPage34)}, 
	{gUrbanPage35, ARRAY_COUNT(gUrbanPage35)}, 
	{gUrbanPage36, ARRAY_COUNT(gUrbanPage36)},
	{gUrbanPage37, ARRAY_COUNT(gUrbanPage37)}, 
};

const struct HabitatPage gRarePages[] =
{
	{gRarePage1, ARRAY_COUNT(gRarePage1)}, 
	{gRarePage2, ARRAY_COUNT(gRarePage2)}, 
	{gRarePage3, ARRAY_COUNT(gRarePage3)}, 
	{gRarePage4, ARRAY_COUNT(gRarePage4)}, 
	{gRarePage5, ARRAY_COUNT(gRarePage5)}, 
	{gRarePage6, ARRAY_COUNT(gRarePage6)}, 
	{gRarePage7, ARRAY_COUNT(gRarePage7)}, 
	{gRarePage8, ARRAY_COUNT(gRarePage8)}, 
	{gRarePage9, ARRAY_COUNT(gRarePage9)}, 
	{gRarePage10, ARRAY_COUNT(gRarePage10)}, 
	{gRarePage11, ARRAY_COUNT(gRarePage11)}, 
	{gRarePage12, ARRAY_COUNT(gRarePage12)}, 
	{gRarePage13, ARRAY_COUNT(gRarePage13)}, 
	{gRarePage14, ARRAY_COUNT(gRarePage14)}, 
	{gRarePage15, ARRAY_COUNT(gRarePage15)}, 
	{gRarePage16, ARRAY_COUNT(gRarePage16)}, 
	{gRarePage17, ARRAY_COUNT(gRarePage17)}, 
	{gRarePage18, ARRAY_COUNT(gRarePage18)},
	{gRarePage19, ARRAY_COUNT(gRarePage19)},
	{gRarePage20, ARRAY_COUNT(gRarePage20)},
	{gRarePage21, ARRAY_COUNT(gRarePage21)},
	{gRarePage22, ARRAY_COUNT(gRarePage22)},
	{gRarePage23, ARRAY_COUNT(gRarePage23)},
	{gRarePage24, ARRAY_COUNT(gRarePage24)},
	{gRarePage25, ARRAY_COUNT(gRarePage25)},
	{gRarePage26, ARRAY_COUNT(gRarePage26)},
	{gRarePage27, ARRAY_COUNT(gRarePage27)},
	{gRarePage28, ARRAY_COUNT(gRarePage28)},
	{gRarePage29, ARRAY_COUNT(gRarePage29)},
	{gRarePage30, ARRAY_COUNT(gRarePage30)},
	{gRarePage31, ARRAY_COUNT(gRarePage31)},
	{gRarePage32, ARRAY_COUNT(gRarePage32)},
	{gRarePage33, ARRAY_COUNT(gRarePage33)},
	{gRarePage34, ARRAY_COUNT(gRarePage34)},
	{gRarePage35, ARRAY_COUNT(gRarePage35)},
	{gRarePage36, ARRAY_COUNT(gRarePage36)},
	{gRarePage37, ARRAY_COUNT(gRarePage37)},
	{gRarePage38 , ARRAY_COUNT(gRarePage38)},
	{gRarePage39 , ARRAY_COUNT(gRarePage39)},
	{gRarePage40 , ARRAY_COUNT(gRarePage40)},
	{gRarePage41 , ARRAY_COUNT(gRarePage41)},
	{gRarePage42 , ARRAY_COUNT(gRarePage42)},
	{gRarePage43 , ARRAY_COUNT(gRarePage43)},
	{gRarePage44 , ARRAY_COUNT(gRarePage44)},
	{gRarePage45 , ARRAY_COUNT(gRarePage45)},
	{gRarePage46 , ARRAY_COUNT(gRarePage46)},
	{gRarePage47 , ARRAY_COUNT(gRarePage47)},
	{gRarePage48 , ARRAY_COUNT(gRarePage48)},
	{gRarePage49 , ARRAY_COUNT(gRarePage49)},
	{gRarePage50 , ARRAY_COUNT(gRarePage50)},
	{gRarePage51 , ARRAY_COUNT(gRarePage51)},
	{gRarePage52 , ARRAY_COUNT(gRarePage52)},
	{gRarePage53 , ARRAY_COUNT(gRarePage53)},
	{gRarePage54 , ARRAY_COUNT(gRarePage54)},
	{gRarePage55 , ARRAY_COUNT(gRarePage55)},
	{gRarePage56 , ARRAY_COUNT(gRarePage56)},
	{gRarePage57 , ARRAY_COUNT(gRarePage57)},
	{gRarePage58 , ARRAY_COUNT(gRarePage58)},
	{gRarePage59 , ARRAY_COUNT(gRarePage59)},
	{gRarePage60 , ARRAY_COUNT(gRarePage60)},
	{gRarePage61 , ARRAY_COUNT(gRarePage61)},
	{gRarePage62 , ARRAY_COUNT(gRarePage62)},
	{gRarePage63 , ARRAY_COUNT(gRarePage63)},
	{gRarePage64 , ARRAY_COUNT(gRarePage64)},
	{gRarePage65 , ARRAY_COUNT(gRarePage65)},
	{gRarePage66 , ARRAY_COUNT(gRarePage66)},
	{gRarePage67 , ARRAY_COUNT(gRarePage67)},
	{gRarePage68 , ARRAY_COUNT(gRarePage68)},
	{gRarePage69 , ARRAY_COUNT(gRarePage69)},
	{gRarePage70 , ARRAY_COUNT(gRarePage70)},
	{gRarePage71 , ARRAY_COUNT(gRarePage71)},
	{gRarePage72 , ARRAY_COUNT(gRarePage72)},
	{gRarePage73 , ARRAY_COUNT(gRarePage73)},
	{gRarePage74 , ARRAY_COUNT(gRarePage74)},
	{gRarePage75 , ARRAY_COUNT(gRarePage75)},
	{gRarePage76 , ARRAY_COUNT(gRarePage76)},
	{gRarePage77 , ARRAY_COUNT(gRarePage77)},
	{gRarePage78 , ARRAY_COUNT(gRarePage78)},
	{gRarePage79 , ARRAY_COUNT(gRarePage79)},
	{gRarePage80 , ARRAY_COUNT(gRarePage80)},
	{gRarePage81 , ARRAY_COUNT(gRarePage81)},
	{gRarePage82 , ARRAY_COUNT(gRarePage82)},
	{gRarePage83 , ARRAY_COUNT(gRarePage83)},
	{gRarePage84 , ARRAY_COUNT(gRarePage84)},
	{gRarePage85 , ARRAY_COUNT(gRarePage85)},
	{gRarePage86 , ARRAY_COUNT(gRarePage86)},
	{gRarePage87 , ARRAY_COUNT(gRarePage87)},
	{gRarePage88 , ARRAY_COUNT(gRarePage88)},
	{gRarePage89 , ARRAY_COUNT(gRarePage89)},
	{gRarePage90 , ARRAY_COUNT(gRarePage90)},
	{gRarePage91 , ARRAY_COUNT(gRarePage91)},
	{gRarePage92 , ARRAY_COUNT(gRarePage92)},
	{gRarePage93 , ARRAY_COUNT(gRarePage93)},
	{gRarePage94 , ARRAY_COUNT(gRarePage94)},
	{gRarePage95 , ARRAY_COUNT(gRarePage95)},
	{gRarePage96 , ARRAY_COUNT(gRarePage96)},
	{gRarePage97 , ARRAY_COUNT(gRarePage97)},
	{gRarePage98 , ARRAY_COUNT(gRarePage98)},
	{gRarePage99 , ARRAY_COUNT(gRarePage99)},
	{gRarePage100, ARRAY_COUNT(gRarePage100)},
	{gRarePage101, ARRAY_COUNT(gRarePage101)},
	{gRarePage102, ARRAY_COUNT(gRarePage102)},
	{gRarePage103, ARRAY_COUNT(gRarePage103)},
	{gRarePage104, ARRAY_COUNT(gRarePage104)},
	{gRarePage105, ARRAY_COUNT(gRarePage105)},
	{gRarePage106, ARRAY_COUNT(gRarePage106)},
	{gRarePage107, ARRAY_COUNT(gRarePage107)},
	{gRarePage108, ARRAY_COUNT(gRarePage108)},
	{gRarePage109, ARRAY_COUNT(gRarePage109)},
	{gRarePage110, ARRAY_COUNT(gRarePage110)},
	{gRarePage111, ARRAY_COUNT(gRarePage111)},
	{gRarePage112, ARRAY_COUNT(gRarePage112)},
	{gRarePage113, ARRAY_COUNT(gRarePage113)},
	{gRarePage114, ARRAY_COUNT(gRarePage114)},
	{gRarePage115, ARRAY_COUNT(gRarePage115)},
	{gRarePage116, ARRAY_COUNT(gRarePage116)},
	{gRarePage117, ARRAY_COUNT(gRarePage117)},
	{gRarePage118, ARRAY_COUNT(gRarePage118)},
	{gRarePage119, ARRAY_COUNT(gRarePage119)},
	{gRarePage120, ARRAY_COUNT(gRarePage120)},
	{gRarePage121, ARRAY_COUNT(gRarePage121)},
	{gRarePage122, ARRAY_COUNT(gRarePage122)},
	{gRarePage123, ARRAY_COUNT(gRarePage123)},
	{gRarePage124, ARRAY_COUNT(gRarePage124)},
	{gRarePage125, ARRAY_COUNT(gRarePage125)},
	{gRarePage126, ARRAY_COUNT(gRarePage126)},
	{gRarePage127, ARRAY_COUNT(gRarePage127)},
	{gRarePage128, ARRAY_COUNT(gRarePage128)},
	{gRarePage129, ARRAY_COUNT(gRarePage129)},
	{gRarePage130, ARRAY_COUNT(gRarePage130)},
	{gRarePage131, ARRAY_COUNT(gRarePage131)},
	{gRarePage132, ARRAY_COUNT(gRarePage132)},
	{gRarePage133, ARRAY_COUNT(gRarePage133)},
	{gRarePage134, ARRAY_COUNT(gRarePage134)},
	{gRarePage135, ARRAY_COUNT(gRarePage135)},
	{gRarePage136, ARRAY_COUNT(gRarePage136)},
	{gRarePage137, ARRAY_COUNT(gRarePage137)},
	{gRarePage138, ARRAY_COUNT(gRarePage138)},
	{gRarePage139, ARRAY_COUNT(gRarePage139)},
	{gRarePage140, ARRAY_COUNT(gRarePage140)},
	{gRarePage141, ARRAY_COUNT(gRarePage141)},
	{gRarePage142, ARRAY_COUNT(gRarePage142)},
	{gRarePage143, ARRAY_COUNT(gRarePage143)},
	{gRarePage144, ARRAY_COUNT(gRarePage144)},
	{gRarePage145, ARRAY_COUNT(gRarePage145)},
	{gRarePage146, ARRAY_COUNT(gRarePage146)},
	{gRarePage147, ARRAY_COUNT(gRarePage147)},
	{gRarePage148, ARRAY_COUNT(gRarePage148)},
	{gRarePage149, ARRAY_COUNT(gRarePage149)},
	{gRarePage150, ARRAY_COUNT(gRarePage150)},
	{gRarePage151, ARRAY_COUNT(gRarePage151)},
	{gRarePage152, ARRAY_COUNT(gRarePage152)},
	{gRarePage153, ARRAY_COUNT(gRarePage153)},
	{gRarePage154, ARRAY_COUNT(gRarePage154)},
	{gRarePage155, ARRAY_COUNT(gRarePage155)},
	{gRarePage156, ARRAY_COUNT(gRarePage156)},
	{gRarePage157, ARRAY_COUNT(gRarePage157)},
	{gRarePage158, ARRAY_COUNT(gRarePage158)},
	{gRarePage159, ARRAY_COUNT(gRarePage159)},
	{gRarePage160, ARRAY_COUNT(gRarePage160)},
	{gRarePage161, ARRAY_COUNT(gRarePage161)},
	{gRarePage162, ARRAY_COUNT(gRarePage162)},
	{gRarePage163, ARRAY_COUNT(gRarePage163)},
	{gRarePage164, ARRAY_COUNT(gRarePage164)},
	{gRarePage165, ARRAY_COUNT(gRarePage165)},
	{gRarePage166, ARRAY_COUNT(gRarePage166)},
	{gRarePage167, ARRAY_COUNT(gRarePage167)},
	{gRarePage168, ARRAY_COUNT(gRarePage168)},
	{gRarePage169, ARRAY_COUNT(gRarePage169)},
	{gRarePage170, ARRAY_COUNT(gRarePage170)},
	{gRarePage171, ARRAY_COUNT(gRarePage171)},
	{gRarePage172, ARRAY_COUNT(gRarePage172)},
	{gRarePage173, ARRAY_COUNT(gRarePage173)},
	{gRarePage174, ARRAY_COUNT(gRarePage174)},
	{gRarePage175, ARRAY_COUNT(gRarePage175)},
	{gRarePage176, ARRAY_COUNT(gRarePage176)},
	{gRarePage177, ARRAY_COUNT(gRarePage177)},
	{gRarePage178, ARRAY_COUNT(gRarePage178)},
	{gRarePage179, ARRAY_COUNT(gRarePage179)},
	{gRarePage180, ARRAY_COUNT(gRarePage180)},
	{gRarePage181, ARRAY_COUNT(gRarePage181)},
	{gRarePage182, ARRAY_COUNT(gRarePage182)},
	{gRarePage183, ARRAY_COUNT(gRarePage183)},
	{gRarePage184, ARRAY_COUNT(gRarePage184)},
	{gRarePage185, ARRAY_COUNT(gRarePage185)},
	{gRarePage186, ARRAY_COUNT(gRarePage186)},
	{gRarePage187, ARRAY_COUNT(gRarePage187)},
	{gRarePage188, ARRAY_COUNT(gRarePage188)},
	{gRarePage189, ARRAY_COUNT(gRarePage189)},
	{gRarePage190, ARRAY_COUNT(gRarePage190)},
	{gRarePage191, ARRAY_COUNT(gRarePage191)},
	{gRarePage192, ARRAY_COUNT(gRarePage192)},
	{gRarePage193, ARRAY_COUNT(gRarePage193)},
	{gRarePage194, ARRAY_COUNT(gRarePage194)},
	{gRarePage195, ARRAY_COUNT(gRarePage195)},
	{gRarePage196, ARRAY_COUNT(gRarePage196)},
	{gRarePage197, ARRAY_COUNT(gRarePage197)},
	{gRarePage198, ARRAY_COUNT(gRarePage198)},
	{gRarePage199, ARRAY_COUNT(gRarePage199)},
	{gRarePage200, ARRAY_COUNT(gRarePage200)},
	{gRarePage201, ARRAY_COUNT(gRarePage201)},
	{gRarePage202, ARRAY_COUNT(gRarePage202)},
	{gRarePage203, ARRAY_COUNT(gRarePage203)},
	{gRarePage204, ARRAY_COUNT(gRarePage204)},
	{gRarePage205, ARRAY_COUNT(gRarePage205)},
	{gRarePage206, ARRAY_COUNT(gRarePage206)},
	{gRarePage207, ARRAY_COUNT(gRarePage207)},
	{gRarePage208, ARRAY_COUNT(gRarePage208)},
	{gRarePage209, ARRAY_COUNT(gRarePage209)},
	{gRarePage210, ARRAY_COUNT(gRarePage210)},
	{gRarePage211, ARRAY_COUNT(gRarePage211)},
	{gRarePage212, ARRAY_COUNT(gRarePage212)},
	{gRarePage213, ARRAY_COUNT(gRarePage213)},
	{gRarePage214, ARRAY_COUNT(gRarePage214)},
	{gRarePage215, ARRAY_COUNT(gRarePage215)},
	{gRarePage216, ARRAY_COUNT(gRarePage216)},
	{gRarePage217, ARRAY_COUNT(gRarePage217)},
	{gRarePage218, ARRAY_COUNT(gRarePage218)},
	{gRarePage219, ARRAY_COUNT(gRarePage219)},
	{gRarePage220, ARRAY_COUNT(gRarePage220)},
	{gRarePage221, ARRAY_COUNT(gRarePage221)},
	{gRarePage222, ARRAY_COUNT(gRarePage222)},
	{gRarePage223, ARRAY_COUNT(gRarePage223)},
	{gRarePage224, ARRAY_COUNT(gRarePage224)},
	{gRarePage225, ARRAY_COUNT(gRarePage225)},
	{gRarePage226, ARRAY_COUNT(gRarePage226)},
	{gRarePage227, ARRAY_COUNT(gRarePage227)},
	{gRarePage228, ARRAY_COUNT(gRarePage228)},
	{gRarePage229, ARRAY_COUNT(gRarePage229)},
	{gRarePage230, ARRAY_COUNT(gRarePage230)},
	{gRarePage231, ARRAY_COUNT(gRarePage231)},
	{gRarePage232, ARRAY_COUNT(gRarePage232)},
	{gRarePage233, ARRAY_COUNT(gRarePage233)},
	{gRarePage234, ARRAY_COUNT(gRarePage234)},
	{gRarePage235, ARRAY_COUNT(gRarePage235)},
	{gRarePage236, ARRAY_COUNT(gRarePage236)},
	{gRarePage237, ARRAY_COUNT(gRarePage237)},
	{gRarePage238, ARRAY_COUNT(gRarePage238)},
};

const struct Habitat gHabitatPtrsTable[9] =
{                                     
	{gGrasslandPages, ARRAY_COUNT(gGrasslandPages)},
	{gForestPages, ARRAY_COUNT(gForestPages)},
	{gWatersEdgePages, ARRAY_COUNT(gWatersEdgePages)},
	{gSeaPages, ARRAY_COUNT(gSeaPages)},
	{gCavePages, ARRAY_COUNT(gCavePages)},
	{gMountainPages, ARRAY_COUNT(gMountainPages)},
	{gRoughTerrainPages, ARRAY_COUNT(gRoughTerrainPages)},
	{gUrbanPages, ARRAY_COUNT(gUrbanPages)},
	{gRarePages, ARRAY_COUNT(gRarePages)},
};